"use client";

import { useState, useRef, useEffect, useCallback } from "react";
import { useParams } from "next/navigation";
import { trackEvent } from "@/lib/analytics";
import AuditPageSEO from "./AuditPageSEO";

type Locale = "en" | "ar";
type FindingStatus = "pass" | "warning" | "fail";
type CategoryStatus = "good" | "warning" | "critical";

interface Finding {
  check: string;
  status: FindingStatus;
  detail: string;
  impact?: "high" | "medium" | "low";
}

interface Category {
  name: string;
  nameAr: string;
  icon: string;
  score: number;
  status: CategoryStatus;
  findings: Finding[];
}

interface TopPriority {
  category: string;
  detail: string;
  impact: string;
}

interface CoreWebVitals {
  lcp: string; lcpMs: number;
  fcp: string; fcpMs: number;
  cls: string; clsValue: number;
  tbt: string; tbtMs: number;
  si: string;
  performanceScore: number;
  accessibilityScore: number;
  bestPracticesScore: number;
  seoScore: number;
  desktopScore: number | null;
}

interface AuditResult {
  overallScore: number;
  url: string;
  statusCode: number;
  loadTimeMs: number;
  categories: Category[];
  topPriorities: TopPriority[];
  summary: string;
  coreWebVitals: CoreWebVitals | null;
  technologies: string[];
  totalChecks: number;
  passed: number;
  warnings: number;
  failed: number;
}

// ─── Scan Steps ───────────────────────────────────────────────────────────────
const STEPS = {
  en: [
    { icon: "🌐", label: "Connecting to website" },
    { icon: "⚡", label: "Google PageSpeed analysis" },
    { icon: "🔍", label: "Scanning SEO elements" },
    { icon: "📱", label: "Mobile friendliness check" },
    { icon: "🔒", label: "Security headers audit" },
    { icon: "📍", label: "Local SEO signals" },
    { icon: "🔗", label: "Broken link detection" },
    { icon: "📊", label: "Compiling your report" },
  ],
  ar: [
    { icon: "🌐", label: "الاتصال بالموقع" },
    { icon: "⚡", label: "تحليل Google PageSpeed" },
    { icon: "🔍", label: "فحص عناصر SEO" },
    { icon: "📱", label: "فحص التوافق مع الجوال" },
    { icon: "🔒", label: "تدقيق رؤوس الأمان" },
    { icon: "📍", label: "إشارات SEO المحلي" },
    { icon: "🔗", label: "كشف الروابط المعطلة" },
    { icon: "📊", label: "إعداد تقريرك" },
  ],
};

// Step completion progress thresholds
const STEP_THRESHOLDS = [8, 22, 36, 49, 61, 72, 82, 92];

const UI = {
  en: {
    badge: "50+ Checks · Real PageSpeed Data · Instant Results",
    h1: "Free Website Audit",
    sub: "Enter your website URL and get a full SEO, performance, security & local marketing analysis in seconds. No signup required.",
    placeholder: "https://yourwebsite.com",
    btnIdle: "Analyze My Website →",
    btnRunning: "Analyzing…",
    scanning: "Scanning",
    complete: "Complete!",
    statsBar: { checks: "Checks", passed: "Passed", warnings: "Warnings", failed: "Critical" },
    overallLabel: "Overall Website Health Score",
    cwvTitle: "Core Web Vitals (Mobile)",
    cwvLcp: "LCP", cwvFcp: "FCP", cwvCls: "CLS", cwvTbt: "TBT",
    cwvPS: "Performance", cwvA11y: "Accessibility", cwvBP: "Best Practices", cwvSEO: "SEO Score",
    cwvDesktop: "Desktop Score",
    techTitle: "Detected Technologies",
    priorities: "Top Priorities",
    summaryLabel: "Executive Summary",
    findings: "Findings",
    statusGood: "Good ✓", statusWarning: "Warning ⚠", statusCritical: "Critical ✗",
    impactHigh: "High Impact", impactMedium: "Medium", impactLow: "Low",
    ctaHeading: "Want us to fix these issues?",
    ctaSub: "Our team can implement all recommendations and grow your online presence.",
    ctaWa: "WhatsApp Us →", ctaCall: "Call +966 56 422 9190",
    pdfBtn: "Download PDF Report",
    tryAgain: "Try Again",
    errorLabel: "Analysis failed",
    errorSub: "Something went wrong. Please try again or contact us via WhatsApp.",
    printTitle: "Website Audit Report",
    printDate: "Report Date", printUrl: "Audited Website",
    printFooter: "Report generated by Local City Solutions | localcitysolutions.com | +966 56 422 9190 | hello@localcitysolutions.com",
    invalidUrl: "Please enter a valid URL (e.g. https://example.com)",
  },
  ar: {
    badge: "أكثر من ٥٠ فحص · بيانات PageSpeed حقيقية · نتائج فورية",
    h1: "تدقيق مجاني لموقعك",
    sub: "أدخل رابط موقعك واحصل على تحليل شامل — SEO، الأداء، الأمان، والتسويق المحلي — في ثوانٍ. بدون تسجيل.",
    placeholder: "https://موقعك.com",
    btnIdle: "← حلّل موقعي",
    btnRunning: "جاري التحليل…",
    scanning: "فحص جارٍ",
    complete: "اكتمل!",
    statsBar: { checks: "فحص", passed: "نجح", warnings: "تحذيرات", failed: "حرج" },
    overallLabel: "النتيجة الإجمالية لصحة الموقع",
    cwvTitle: "Core Web Vitals (جوال)",
    cwvLcp: "LCP", cwvFcp: "FCP", cwvCls: "CLS", cwvTbt: "TBT",
    cwvPS: "الأداء", cwvA11y: "إمكانية الوصول", cwvBP: "أفضل الممارسات", cwvSEO: "نتيجة SEO",
    cwvDesktop: "نتيجة سطح المكتب",
    techTitle: "التقنيات المكتشفة",
    priorities: "أهم الأولويات",
    summaryLabel: "الملخص التنفيذي",
    findings: "النتائج",
    statusGood: "جيد ✓", statusWarning: "تحذير ⚠", statusCritical: "حرج ✗",
    impactHigh: "تأثير عالٍ", impactMedium: "متوسط", impactLow: "منخفض",
    ctaHeading: "تبي نصلح هذي المشاكل؟",
    ctaSub: "فريقنا يقدر ينفذ كل التوصيات وينمي تواجدك الرقمي.",
    ctaWa: "← واتساب", ctaCall: "اتصل +966 56 422 9190",
    pdfBtn: "تحميل التقرير PDF",
    tryAgain: "حاول مرة أخرى",
    errorLabel: "فشل التحليل",
    errorSub: "حدث خطأ. يرجى المحاولة مرة أخرى أو تواصل معنا عبر واتساب.",
    printTitle: "تقرير تدقيق الموقع الإلكتروني",
    printDate: "تاريخ التقرير", printUrl: "الموقع المُدقق",
    printFooter: "تقرير من لوكال سيتي سولوشنز | localcitysolutions.com | +966 56 422 9190 | hello@localcitysolutions.com",
    invalidUrl: "يرجى إدخال رابط صحيح (مثال: https://example.com)",
  },
};

// ─── Score Ring ───────────────────────────────────────────────────────────────
function ScoreRing({ score, size = 120, stroke = 8 }: { score: number; size?: number; stroke?: number }) {
  const [displayed, setDisplayed] = useState(0);
  const r = (size - stroke) / 2;
  const circ = 2 * Math.PI * r;
  const color = score >= 80 ? "#22c55e" : score >= 50 ? "#F5C518" : "#ef4444";

  useEffect(() => {
    let start: number | null = null;
    const step = (ts: number) => {
      if (!start) start = ts;
      const p = Math.min((ts - start) / 1000, 1);
      setDisplayed(Math.round(p * score));
      if (p < 1) requestAnimationFrame(step);
    };
    requestAnimationFrame(step);
  }, [score]);

  const offset = circ - (displayed / 100) * circ;
  return (
    <svg width={size} height={size} className="rotate-[-90deg]">
      <circle cx={size / 2} cy={size / 2} r={r} fill="none" stroke="rgba(255,255,255,0.08)" strokeWidth={stroke} />
      <circle cx={size / 2} cy={size / 2} r={r} fill="none" stroke={color} strokeWidth={stroke}
        strokeDasharray={circ} strokeDashoffset={offset} strokeLinecap="round"
        style={{ transition: "stroke-dashoffset 0.04s linear" }} />
      <text x={size / 2} y={size / 2 + 1} textAnchor="middle" dominantBaseline="middle"
        fill={color} fontSize={size * 0.22} fontWeight="800"
        style={{ transform: "rotate(90deg)", transformOrigin: `${size / 2}px ${size / 2}px` }}>
        {displayed}
      </text>
    </svg>
  );
}

function MiniRing({ score, size = 44 }: { score: number; size?: number }) {
  const [d, setD] = useState(0);
  const stroke = 4;
  const r = (size - stroke) / 2;
  const circ = 2 * Math.PI * r;
  const color = score >= 80 ? "#22c55e" : score >= 50 ? "#F5C518" : "#ef4444";
  useEffect(() => {
    let s: number | null = null;
    const step = (ts: number) => {
      if (!s) s = ts;
      const p = Math.min((ts - s) / 800, 1);
      setD(Math.round(p * score));
      if (p < 1) requestAnimationFrame(step);
    };
    requestAnimationFrame(step);
  }, [score]);
  const offset = circ - (d / 100) * circ;
  return (
    <svg width={size} height={size} className="rotate-[-90deg] shrink-0">
      <circle cx={size / 2} cy={size / 2} r={r} fill="none" stroke="rgba(255,255,255,0.08)" strokeWidth={stroke} />
      <circle cx={size / 2} cy={size / 2} r={r} fill="none" stroke={color} strokeWidth={stroke}
        strokeDasharray={circ} strokeDashoffset={offset} strokeLinecap="round"
        style={{ transition: "stroke-dashoffset 0.04s linear" }} />
      <text x={size / 2} y={size / 2 + 0.5} textAnchor="middle" dominantBaseline="middle"
        fill={color} fontSize={10} fontWeight="700"
        style={{ transform: "rotate(90deg)", transformOrigin: `${size / 2}px ${size / 2}px` }}>
        {d}
      </text>
    </svg>
  );
}

// ─── Scanner Animation ────────────────────────────────────────────────────────
function ScannerAnimation({
  domain, progress, steps, isAr, isDone,
}: {
  domain: string;
  progress: number;
  steps: { icon: string; label: string }[];
  isAr: boolean;
  isDone: boolean;
}) {
  const size = 220;
  const stroke = 10;
  const r = (size - stroke) / 2;
  const circ = 2 * Math.PI * r;
  const color = isDone ? "#22c55e" : "#F5C518";
  const offset = circ - (progress / 100) * circ;

  const completedCount = STEP_THRESHOLDS.filter((t) => progress >= t).length;
  const currentStep = isDone ? steps.length - 1 : Math.min(completedCount, steps.length - 1);

  return (
    <div className="flex flex-col items-center py-8 px-4">
      {/* Domain pill */}
      <div className="flex items-center gap-2 px-4 py-2 rounded-full bg-white/[0.05] border border-white/10 mb-8 max-w-xs overflow-hidden">
        <span className="relative flex h-2 w-2 shrink-0">
          <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-[#F5C518] opacity-75" />
          <span className="relative inline-flex rounded-full h-2 w-2 bg-[#F5C518]" />
        </span>
        <span className="text-white/50 text-xs font-mono truncate" dir="ltr">{domain}</span>
      </div>

      {/* Main ring */}
      <div className="relative mb-6" style={{ width: size, height: size }}>
        {/* Outer decorative dashed ring */}
        <svg className="absolute inset-0 opacity-20" width={size} height={size}
          style={{ animation: "spin-slow 12s linear infinite" }}>
          <circle cx={size / 2} cy={size / 2} r={r + 18} fill="none"
            stroke="#F5C518" strokeWidth="1" strokeDasharray="4 8" strokeLinecap="round" />
        </svg>

        {/* Ping rings */}
        {!isDone && (
          <>
            <div className="absolute inset-0 rounded-full border border-[#F5C518]/20"
              style={{ animation: "ping-ring 2.5s ease-out infinite" }} />
            <div className="absolute inset-0 rounded-full border border-[#F5C518]/10"
              style={{ animation: "ping-ring 2.5s ease-out 1.25s infinite" }} />
          </>
        )}

        {/* Radar sweep */}
        {!isDone && (
          <div className="absolute inset-0 rounded-full overflow-hidden opacity-25"
            style={{ animation: "spin-fast 2s linear infinite" }}>
            <div className="w-full h-full rounded-full"
              style={{
                background: "conic-gradient(from 0deg, transparent 0deg, rgba(245,197,24,0.8) 60deg, transparent 60deg)",
              }} />
          </div>
        )}

        {/* Progress ring SVG */}
        <svg width={size} height={size} className="rotate-[-90deg]">
          <circle cx={size / 2} cy={size / 2} r={r} fill="none"
            stroke="rgba(255,255,255,0.06)" strokeWidth={stroke} />
          <circle cx={size / 2} cy={size / 2} r={r} fill="none"
            stroke={color} strokeWidth={stroke}
            strokeDasharray={circ} strokeDashoffset={offset} strokeLinecap="round"
            style={{
              transition: "stroke-dashoffset 0.3s ease, stroke 0.5s ease",
              filter: `drop-shadow(0 0 ${isDone ? "14px" : "8px"} ${isDone ? "rgba(34,197,94,0.7)" : "rgba(245,197,24,0.5)"})`,
            }} />
        </svg>

        {/* Center content */}
        <div className="absolute inset-0 flex flex-col items-center justify-center text-center gap-1">
          <div className="text-3xl leading-none" style={{ filter: "drop-shadow(0 0 6px rgba(245,197,24,0.5))" }}>
            {isDone ? "✅" : steps[currentStep]?.icon}
          </div>
          <div className={`text-4xl font-black leading-none ${isDone ? "text-green-400" : "text-white"}`}
            style={{ fontVariantNumeric: "tabular-nums" }}>
            {Math.round(progress)}
            <span className="text-xl">%</span>
          </div>
          <div className="text-white/30 text-[10px] uppercase tracking-widest">
            {isAr ? (isDone ? "اكتمل" : "فحص جارٍ") : (isDone ? "Complete" : "Scanning")}
          </div>
        </div>
      </div>

      {/* Current step label */}
      <p className={`text-sm font-semibold mb-6 text-center min-h-[20px] transition-all duration-500 ${isDone ? "text-green-400" : "text-[#F5C518]"}`}>
        {isDone
          ? (isAr ? "تم التحليل بنجاح!" : "Analysis complete!")
          : steps[currentStep]?.label}
      </p>

      {/* Steps grid */}
      <div className="grid grid-cols-2 gap-2 w-full max-w-xs">
        {steps.map((step, i) => {
          const done = progress >= STEP_THRESHOLDS[i];
          const active = !done && i === currentStep;
          return (
            <div key={i}
              className={`flex items-center gap-2 px-3 py-2 rounded-lg text-xs transition-all duration-500 ${
                done
                  ? "bg-green-400/10 border border-green-400/20 text-green-300"
                  : active
                  ? "bg-[#F5C518]/10 border border-[#F5C518]/30 text-[#F5C518]"
                  : "bg-white/[0.03] border border-white/5 text-white/20"
              }`}>
              <span className="text-base shrink-0 leading-none">
                {done ? "✓" : step.icon}
              </span>
              <span className="leading-tight">{step.label}</span>
            </div>
          );
        })}
      </div>
    </div>
  );
}

// ─── Page Component ───────────────────────────────────────────────────────────
export default function FreeAuditPage() {
  const params = useParams();
  const locale = (params?.locale as Locale) || "en";
  const isAr = locale === "ar";
  const t = UI[locale] || UI.en;
  const steps = STEPS[locale] || STEPS.en;

  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [auditResult, setAuditResult] = useState<AuditResult | null>(null);
  const [error, setError] = useState("");
  const [auditedUrl, setAuditedUrl] = useState("");
  const [urlValue, setUrlValue] = useState("");
  const [urlError, setUrlError] = useState("");
  const [progress, setProgress] = useState(0);
  const [apiDone, setApiDone] = useState(false);
  const [expandedCards, setExpandedCards] = useState<Record<string, boolean>>({});

  const reportRef = useRef<HTMLDivElement>(null);
  const progressRef = useRef(0);
  const apiDoneRef = useRef(false);

  // ─── Progress simulation ──────────────────────────────────────────────────
  useEffect(() => {
    if (!isAnalyzing) return;
    progressRef.current = 0;
    apiDoneRef.current = false;
    setProgress(0);

    const startTime = Date.now();
    const tick = setInterval(() => {
      const elapsed = (Date.now() - startTime) / 1000;
      let target: number;
      if (apiDoneRef.current) {
        target = 100;
      } else if (elapsed < 5) {
        target = (elapsed / 5) * 22;
      } else if (elapsed < 30) {
        target = 22 + ((elapsed - 5) / 25) * 58;
      } else {
        target = Math.min(90, 80 + ((elapsed - 30) / 20) * 10);
      }

      const current = progressRef.current;
      const next = Math.min(target, current + (apiDoneRef.current ? 3 : 0.4));
      progressRef.current = next;
      setProgress(next);

      if (next >= 100) clearInterval(tick);
    }, 60);

    return () => clearInterval(tick);
  }, [isAnalyzing]);

  function toggleCard(name: string) {
    setExpandedCards((p) => ({ ...p, [name]: !p[name] }));
  }

  const validateUrl = useCallback((val: string) => {
    try {
      const u = new URL(val);
      return u.protocol === "http:" || u.protocol === "https:";
    } catch {
      return false;
    }
  }, []);

  async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    const websiteUrl = urlValue.trim();

    let finalUrl = websiteUrl;
    if (finalUrl && !finalUrl.startsWith("http")) finalUrl = "https://" + finalUrl;

    if (!validateUrl(finalUrl)) {
      setUrlError(t.invalidUrl);
      return;
    }
    setUrlError("");

    setIsAnalyzing(true);
    setError("");
    setAuditResult(null);
    setApiDone(false);
    setExpandedCards({});
    setAuditedUrl(finalUrl);

    // Fire-and-forget URL tracking
    const w3 = new FormData();
    w3.append("access_key", "f3331300-e0d7-4572-9c9d-69ce21d88b26");
    w3.append("subject", "New Free Audit Lead — LCS");
    w3.append("from_name", "LCS Audit Tool");
    w3.append("name", "Website Audit User");
    w3.append("email", "audit@tool.lcs");
    w3.append("Website URL", finalUrl);
    fetch("https://api.web3forms.com/submit", { method: "POST", body: w3 });

    trackEvent("audit_started", { url: finalUrl });

    try {
      const auditRes = await fetch("/api/audit", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url: finalUrl }),
      });

      if (!auditRes.ok) {
        const errBody = await auditRes.json().catch(() => ({}));
        throw new Error(errBody?.error || `API returned ${auditRes.status}`);
      }

      const result: AuditResult = await auditRes.json();
      apiDoneRef.current = true;
      setApiDone(true);

      // Let the progress animate to 100% before showing results
      await new Promise((res) => setTimeout(res, 900));

      setAuditResult(result);
      trackEvent("audit_completed", { url: finalUrl, score: result.overallScore });

      setTimeout(() => {
        reportRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
      }, 200);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Unknown error";
      setError(`${t.errorSub} (${msg})`);
    } finally {
      setIsAnalyzing(false);
    }
  }

  function handleDownloadPDF() {
    if (!auditResult) return;
    trackEvent("audit_pdf_download", { url: auditResult.url, score: auditResult.overallScore });

    const getStatusIcon = (status: string) =>
      status === "pass" ? "✅" : status === "warning" ? "⚠️" : "❌";
    const getScoreColor = (score: number) =>
      score >= 80 ? "#22C55E" : score >= 50 ? "#F5C518" : "#EF4444";

    const categoriesHTML = auditResult.categories.map((cat) => `
      <div style="margin-bottom:24px;border:1px solid #e5e7eb;border-radius:8px;padding:16px;break-inside:avoid;">
        <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px;">
          <h3 style="margin:0;font-size:16px;color:#1a1a1a;">${cat.icon} ${cat.name}</h3>
          <span style="font-size:20px;font-weight:bold;color:${getScoreColor(cat.score)};">${cat.score}/100</span>
        </div>
        <table style="width:100%;border-collapse:collapse;font-size:12px;">
          <tbody>
            ${cat.findings.map((f) => `
              <tr style="border-bottom:1px solid #f3f4f6;">
                <td style="padding:6px 8px;width:24px;">${getStatusIcon(f.status)}</td>
                <td style="padding:6px 8px;font-weight:600;color:#374151;width:160px;">${f.check}</td>
                <td style="padding:6px 8px;color:#6b7280;">${f.detail}</td>
              </tr>`).join("")}
          </tbody>
        </table>
      </div>`).join("");

    const prioritiesHTML = auditResult.topPriorities.map((p, i) => `
      <div style="padding:8px 12px;margin-bottom:8px;background:#FFF7E6;border-left:3px solid #F5C518;border-radius:4px;">
        <strong>${i + 1}.</strong> <strong>${p.category}:</strong> ${p.detail}
      </div>`).join("");

    const cwvHTML = auditResult.coreWebVitals ? `
      <div style="margin-bottom:24px;padding:16px;border:2px solid #F5C518;border-radius:8px;background:#FFFBEB;">
        <h3 style="margin:0 0 12px 0;color:#1a1a1a;">Core Web Vitals (Google PageSpeed)</h3>
        <table style="width:100%;border-collapse:collapse;font-size:13px;">
          <tr>
            <td style="padding:6px 12px;"><strong>LCP:</strong> ${auditResult.coreWebVitals.lcp}</td>
            <td style="padding:6px 12px;"><strong>FCP:</strong> ${auditResult.coreWebVitals.fcp}</td>
            <td style="padding:6px 12px;"><strong>CLS:</strong> ${auditResult.coreWebVitals.cls}</td>
          </tr>
          <tr>
            <td style="padding:6px 12px;"><strong>TBT:</strong> ${auditResult.coreWebVitals.tbt}</td>
            <td style="padding:6px 12px;"><strong>Performance:</strong> ${auditResult.coreWebVitals.performanceScore}/100</td>
          </tr>
        </table>
      </div>` : "";

    const techHTML = auditResult.technologies?.length > 0 ? `
      <div style="margin-bottom:24px;">
        <h3 style="color:#1a1a1a;margin-bottom:8px;">Technologies Detected</h3>
        <div style="display:flex;flex-wrap:wrap;gap:6px;">
          ${auditResult.technologies.map((tech) =>
            `<span style="background:#f3f4f6;padding:4px 10px;border-radius:12px;font-size:12px;color:#374151;">${tech}</span>`
          ).join("")}
        </div>
      </div>` : "";

    const currentDate = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

    const fullHTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Website Audit Report — ${auditResult.url}</title>
  <style>
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family:'Segoe UI',Arial,sans-serif; color:#1a1a1a; padding:40px; line-height:1.6; font-size:13px; }
    .header { display:flex; justify-content:space-between; align-items:center; border-bottom:3px solid #F5C518; padding-bottom:16px; margin-bottom:24px; }
    .logo { font-size:22px; font-weight:bold; color:#0A1628; }
    .logo span { color:#F5C518; }
    .header-right { text-align:right; font-size:11px; color:#6b7280; }
    .report-title { text-align:center; margin-bottom:24px; }
    .report-title h1 { font-size:24px; color:#0A1628; margin-bottom:4px; }
    .report-title .url { font-size:14px; color:#F5C518; }
    .report-title .date { font-size:12px; color:#9ca3af; margin-top:4px; }
    .score-section { text-align:center; margin-bottom:30px; padding:24px; background:#f9fafb; border-radius:12px; }
    .overall-score { font-size:64px; font-weight:bold; }
    .stats { display:flex; justify-content:center; gap:32px; margin-top:12px; }
    .stat { text-align:center; }
    .stat-val { font-size:24px; font-weight:bold; }
    .stat-lbl { font-size:11px; color:#6b7280; }
    .section-title { font-size:18px; font-weight:bold; color:#0A1628; margin:24px 0 12px; border-bottom:2px solid #f3f4f6; padding-bottom:8px; }
    .footer { margin-top:32px; padding-top:16px; border-top:1px solid #e5e7eb; font-size:11px; color:#6b7280; text-align:center; }
    @media print { body { padding:20px; } }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">Local City <span>Solutions</span></div>
    <div class="header-right">
      <div>${t.printTitle}</div>
      <div>${t.printDate}: ${currentDate}</div>
      <div>${t.printUrl}: ${auditResult.url}</div>
    </div>
  </div>
  <div class="score-section">
    <div class="overall-score" style="color:${getScoreColor(auditResult.overallScore)}">
      ${auditResult.overallScore}<span style="font-size:32px;">/100</span>
    </div>
    <div class="stats">
      <div class="stat"><div class="stat-val">${auditResult.totalChecks}</div><div class="stat-lbl">${t.statsBar.checks}</div></div>
      <div class="stat"><div class="stat-val" style="color:#22C55E">${auditResult.passed}</div><div class="stat-lbl">${t.statsBar.passed}</div></div>
      <div class="stat"><div class="stat-val" style="color:#F5C518">${auditResult.warnings}</div><div class="stat-lbl">${t.statsBar.warnings}</div></div>
      <div class="stat"><div class="stat-val" style="color:#EF4444">${auditResult.failed}</div><div class="stat-lbl">${t.statsBar.failed}</div></div>
    </div>
  </div>
  ${cwvHTML}
  ${techHTML}
  <div class="section-title">${t.priorities}</div>
  ${prioritiesHTML}
  <div class="section-title">${t.summaryLabel}</div>
  <p style="color:#6b7280;margin-bottom:24px;">${auditResult.summary}</p>
  <div class="section-title">${t.findings}</div>
  ${categoriesHTML}
  <div class="footer">
    <p><strong>Report generated by Local City Solutions</strong></p>
    <p>localcitysolutions.com · +966 56 422 9190 · hello@localcitysolutions.com</p>
  </div>
</body>
</html>`;

    const printWindow = window.open("", "_blank", "width=900,height=700");
    if (printWindow) {
      printWindow.document.write(fullHTML);
      printWindow.document.close();
      printWindow.onload = () => { setTimeout(() => printWindow.print(), 500); };
      setTimeout(() => printWindow.print(), 1500);
    }
  }

  const catStatusStyle = (s: CategoryStatus) =>
    s === "good" ? "text-green-400 bg-green-400/10 border-green-400/20"
    : s === "warning" ? "text-[#F5C518] bg-[#F5C518]/10 border-[#F5C518]/20"
    : "text-red-400 bg-red-400/10 border-red-400/20";

  const catStatusLabel = (s: CategoryStatus) =>
    s === "good" ? t.statusGood : s === "warning" ? t.statusWarning : t.statusCritical;

  const findingDot = (s: FindingStatus) =>
    s === "pass" ? "bg-green-400" : s === "warning" ? "bg-[#F5C518]" : "bg-red-400";

  const cwvColor = (ms: number, thresholds: [number, number]) =>
    ms < thresholds[0] ? "text-green-400" : ms < thresholds[1] ? "text-[#F5C518]" : "text-red-400";

  const psColor = (s: number) =>
    s >= 90 ? "text-green-400" : s >= 50 ? "text-[#F5C518]" : "text-red-400";

  const domain = auditedUrl ? auditedUrl.replace(/^https?:\/\//, "").split("/")[0] : "";

  return (
    <>
      <style>{`
        @keyframes spin-slow {
          from { transform: rotate(0deg); }
          to   { transform: rotate(360deg); }
        }
        @keyframes spin-fast {
          from { transform: rotate(0deg); }
          to   { transform: rotate(360deg); }
        }
        @keyframes ping-ring {
          0%   { transform: scale(1);   opacity: 0.5; }
          100% { transform: scale(1.6); opacity: 0; }
        }
      `}</style>

      {/* HERO */}
      <section id="audit-hero" className="relative bg-[#080E1A] pt-28 md:pt-36 pb-10 overflow-hidden" dir={isAr ? "rtl" : "ltr"}>
        <div className="absolute inset-0 pointer-events-none"
          style={{ background: "radial-gradient(ellipse 70% 50% at 50% 0%, rgba(245,197,24,0.07) 0%, transparent 70%)" }} />
        <div className="relative max-w-3xl mx-auto px-4 sm:px-6 text-center">
          <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-[#F5C518]/25 bg-[#F5C518]/[0.08] text-[#F5C518] text-[11px] font-bold uppercase tracking-[0.12em] mb-5">
            <span className="w-1.5 h-1.5 rounded-full bg-[#F5C518] animate-pulse shrink-0" />
            {t.badge}
          </span>
          <h1 className="text-3xl md:text-5xl font-black text-white mb-4 leading-tight">{t.h1}</h1>
          <p className="text-white/55 text-base md:text-lg max-w-2xl mx-auto">{t.sub}</p>
        </div>
      </section>

      {/* FORM / SCANNER */}
      <section className="bg-[#080E1A] pb-16 md:pb-20" dir={isAr ? "rtl" : "ltr"}>
        <div className="max-w-2xl mx-auto px-4 sm:px-6">

          {/* URL form — hidden while analyzing */}
          {!isAnalyzing && !auditResult && (
            <form onSubmit={handleSubmit} noValidate>
              <div className="bg-[#0E1A2E] border border-white/[0.07] rounded-2xl p-6 md:p-8">
                {/* URL input row */}
                <div className="flex flex-col sm:flex-row gap-3">
                  <div className="relative flex-1">
                    {/* Globe icon */}
                    <svg className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-white/30 pointer-events-none"
                      fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round"
                        d="M12 21a9 9 0 100-18 9 9 0 000 18zm0 0c-2.5 0-4.5-4-4.5-9S9.5 3 12 3m0 18c2.5 0 4.5-4 4.5-9S14.5 3 12 3M3.5 12h17" />
                    </svg>
                    <input
                      type="text"
                      value={urlValue}
                      onChange={(e) => { setUrlValue(e.target.value); setUrlError(""); }}
                      placeholder={t.placeholder}
                      dir="ltr"
                      className={`w-full bg-[#080E1A] border rounded-xl pl-10 pr-4 py-3.5 text-white placeholder-white/25 text-sm focus:outline-none transition-colors ${
                        urlError ? "border-red-400/50 focus:border-red-400" : "border-white/10 focus:border-[#F5C518]/50"
                      }`}
                    />
                  </div>
                  <button
                    type="submit"
                    className="sm:w-auto px-6 py-3.5 rounded-xl bg-[#F5C518] text-[#080E1A] font-bold text-sm hover:bg-[#F5C518]/90 transition-all shadow-xl shadow-[#F5C518]/20 whitespace-nowrap flex items-center justify-center gap-2"
                  >
                    {t.btnIdle}
                  </button>
                </div>
                {urlError && (
                  <p className="text-red-400 text-xs mt-2 px-1">{urlError}</p>
                )}
                {/* Trust signals */}
                <div className="flex flex-wrap items-center gap-x-4 gap-y-1 mt-4 text-white/30 text-[11px]">
                  <span className="flex items-center gap-1">
                    <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    {isAr ? "مجاني بالكامل" : "Completely free"}
                  </span>
                  <span className="flex items-center gap-1">
                    <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    {isAr ? "لا تسجيل مطلوب" : "No signup required"}
                  </span>
                  <span className="flex items-center gap-1">
                    <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                    {isAr ? "نتائج خلال ٦٠ ثانية" : "Results in ~60 seconds"}
                  </span>
                </div>
              </div>
            </form>
          )}

          {/* Scanner animation — visible while analyzing */}
          {isAnalyzing && (
            <div className="bg-[#0E1A2E] border border-white/[0.07] rounded-2xl overflow-hidden">
              <ScannerAnimation
                domain={domain}
                progress={progress}
                steps={steps}
                isAr={isAr}
                isDone={apiDone && progress >= 99}
              />
            </div>
          )}

          {/* Error */}
          {error && !isAnalyzing && (
            <div className={`mt-6 p-4 rounded-xl border border-red-400/20 bg-red-400/[0.05] ${isAr ? "text-right" : ""}`}>
              <p className="text-red-400 font-semibold text-sm mb-1">{t.errorLabel}</p>
              <p className="text-white/60 text-sm mb-3">{error}</p>
              <div className="flex gap-3 flex-wrap">
                <button
                  onClick={() => { setError(""); setAuditResult(null); }}
                  className="text-sm px-4 py-2 rounded-lg border border-white/15 text-white/70 hover:border-white/30 transition-colors">
                  {t.tryAgain}
                </button>
                <a href="https://wa.me/966564229190" target="_blank" rel="noopener noreferrer"
                  className="text-sm px-4 py-2 rounded-lg bg-[#25D366]/10 border border-[#25D366]/20 text-[#25D366] hover:bg-[#25D366]/20 transition-colors">
                  WhatsApp
                </a>
              </div>
            </div>
          )}
        </div>
      </section>

      {/* AUDIT REPORT */}
      {auditResult && (
        <section ref={reportRef} className="bg-[#0C1424] py-12 md:py-16" dir={isAr ? "rtl" : "ltr"}>
          <div className="max-w-5xl mx-auto px-4 sm:px-6 space-y-10">

            {/* Try another URL */}
            <div className={`flex ${isAr ? "justify-end" : "justify-start"}`}>
              <button
                onClick={() => { setAuditResult(null); setError(""); setProgress(0); setApiDone(false); }}
                className="inline-flex items-center gap-2 text-white/40 text-xs hover:text-white/70 transition-colors">
                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                </svg>
                {isAr ? "تحليل موقع آخر" : "Analyze another URL"}
              </button>
            </div>

            {/* Overall Score */}
            <div className="flex flex-col items-center text-center">
              <ScoreRing score={auditResult.overallScore} size={150} stroke={11} />
              <p className="text-white/55 text-sm mt-3 mb-1">{t.overallLabel}</p>
              <p className="text-white/30 text-xs" dir="ltr">{auditedUrl}</p>
            </div>

            {/* Stats bar */}
            <div className="grid grid-cols-4 gap-3">
              {[
                { label: t.statsBar.checks, val: auditResult.totalChecks, color: "text-white" },
                { label: t.statsBar.passed, val: auditResult.passed, color: "text-green-400" },
                { label: t.statsBar.warnings, val: auditResult.warnings, color: "text-[#F5C518]" },
                { label: t.statsBar.failed, val: auditResult.failed, color: "text-red-400" },
              ].map(({ label, val, color }) => (
                <div key={label} className="bg-[#0E1A2E] border border-white/[0.07] rounded-xl p-3 md:p-4 text-center">
                  <div className={`text-xl md:text-3xl font-black ${color}`}>{val}</div>
                  <div className="text-white/40 text-[10px] md:text-xs mt-1">{label}</div>
                </div>
              ))}
            </div>

            {/* Core Web Vitals */}
            {auditResult.coreWebVitals && (
              <div className="bg-[#0E1A2E] border border-white/[0.07] rounded-2xl p-5 md:p-6">
                <h2 className="text-white font-bold text-base md:text-lg mb-5">{t.cwvTitle}</h2>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-5">
                  {[
                    { key: t.cwvLcp, val: auditResult.coreWebVitals.lcp, color: cwvColor(auditResult.coreWebVitals.lcpMs, [2500, 4000]) },
                    { key: t.cwvFcp, val: auditResult.coreWebVitals.fcp, color: cwvColor(auditResult.coreWebVitals.fcpMs, [1800, 3000]) },
                    { key: t.cwvCls, val: auditResult.coreWebVitals.cls, color: cwvColor(auditResult.coreWebVitals.clsValue * 1000, [100, 250]) },
                    { key: t.cwvTbt, val: auditResult.coreWebVitals.tbt, color: cwvColor(auditResult.coreWebVitals.tbtMs, [200, 600]) },
                  ].map(({ key, val, color }) => (
                    <div key={key} className="bg-[#080E1A] rounded-xl p-3 text-center">
                      <div className={`text-lg md:text-2xl font-black ${color}`} dir="ltr">{val}</div>
                      <div className="text-white/40 text-[10px] mt-1">{key}</div>
                    </div>
                  ))}
                </div>
                <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
                  {[
                    { key: t.cwvPS, val: auditResult.coreWebVitals.performanceScore },
                    { key: t.cwvA11y, val: auditResult.coreWebVitals.accessibilityScore },
                    { key: t.cwvBP, val: auditResult.coreWebVitals.bestPracticesScore },
                    { key: t.cwvSEO, val: auditResult.coreWebVitals.seoScore },
                    ...(auditResult.coreWebVitals.desktopScore !== null
                      ? [{ key: t.cwvDesktop, val: auditResult.coreWebVitals.desktopScore }]
                      : []),
                  ].map(({ key, val }) => (
                    <div key={key} className="bg-[#080E1A] rounded-xl p-3 text-center">
                      <div className={`text-xl font-black ${psColor(val)}`}>{val}</div>
                      <div className="text-white/40 text-[10px] mt-1">{key}</div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Technologies */}
            {auditResult.technologies.length > 0 && (
              <div>
                <h2 className="text-white font-bold text-sm mb-3">{t.techTitle}</h2>
                <div className="flex flex-wrap gap-2">
                  {auditResult.technologies.map((tech) => (
                    <span key={tech} className="px-3 py-1 rounded-full bg-[#0E1A2E] border border-white/10 text-white/60 text-xs">
                      {tech}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {/* Category Cards */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {auditResult.categories.map((cat) => {
                const isExpanded = expandedCards[cat.name] !== false;
                const passes = cat.findings.filter((f) => f.status === "pass").length;
                const fails = cat.findings.filter((f) => f.status === "fail").length;
                const warns = cat.findings.filter((f) => f.status === "warning").length;
                return (
                  <div key={cat.name}
                    className="bg-[#0E1A2E] border border-white/[0.07] rounded-xl overflow-hidden hover:border-[#F5C518]/20 transition-all">
                    <button onClick={() => toggleCard(cat.name)}
                      className="w-full flex items-center justify-between p-4 md:p-5 text-left">
                      <div className="flex items-center gap-3">
                        <MiniRing score={cat.score} />
                        <div>
                          <div className="text-white font-bold text-sm">
                            <span className="mr-1.5">{cat.icon}</span>
                            {isAr ? cat.nameAr : cat.name}
                          </div>
                          <div className="flex gap-2 mt-0.5">
                            <span className="text-green-400 text-[10px]">{passes}✓</span>
                            <span className="text-[#F5C518] text-[10px]">{warns}⚠</span>
                            <span className="text-red-400 text-[10px]">{fails}✗</span>
                          </div>
                        </div>
                      </div>
                      <div className="flex items-center gap-2">
                        <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full border ${catStatusStyle(cat.status)}`}>
                          {catStatusLabel(cat.status)}
                        </span>
                        <svg className={`w-4 h-4 text-white/30 transition-transform ${isExpanded ? "rotate-180" : ""}`}
                          fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
                        </svg>
                      </div>
                    </button>
                    {isExpanded && (
                      <div className="px-4 md:px-5 pb-4 space-y-2 border-t border-white/[0.05] pt-3">
                        {cat.findings.map((f, i) => (
                          <div key={i} className="flex items-start gap-2.5">
                            <span className={`w-1.5 h-1.5 rounded-full shrink-0 mt-1.5 ${findingDot(f.status)}`} />
                            <div className="flex-1 min-w-0">
                              <span className="text-white/45 text-[11px] font-semibold mr-1.5">{f.check}:</span>
                              <span className="text-white/60 text-[11px] leading-relaxed">{f.detail}</span>
                              {f.impact === "high" && (
                                <span className="ml-1.5 text-[9px] px-1.5 py-0.5 rounded bg-red-400/10 text-red-400 font-bold">
                                  {t.impactHigh}
                                </span>
                              )}
                            </div>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>

            {/* Top Priorities */}
            <div className={`bg-[#0E1A2E] rounded-xl py-5 px-5 ${isAr ? "border-r-[3px] border-r-[#F5C518]/60 rounded-l-xl" : "border-l-[3px] border-l-[#F5C518]/60 rounded-r-xl"}`}>
              <h2 className="text-white font-bold text-lg mb-4">{t.priorities}</h2>
              <ol className="space-y-3">
                {auditResult.topPriorities.map((p, i) => (
                  <li key={i} className="flex gap-3 items-start">
                    <span className="w-6 h-6 rounded-full bg-[#F5C518]/10 border border-[#F5C518]/25 text-[#F5C518] text-xs font-bold flex items-center justify-center shrink-0 mt-0.5">
                      {i + 1}
                    </span>
                    <div>
                      <span className="text-[#F5C518]/70 text-[10px] font-semibold uppercase tracking-wide">{p.category} · </span>
                      <span className="text-white/75 text-sm leading-relaxed">{p.detail}</span>
                    </div>
                  </li>
                ))}
              </ol>
            </div>

            {/* Summary */}
            <div className="bg-[#0E1A2E] border border-white/[0.07] rounded-xl p-5 md:p-6">
              <h2 className="text-white font-bold text-lg mb-3">{t.summaryLabel}</h2>
              <p className="text-white/60 text-sm leading-relaxed">{auditResult.summary}</p>
            </div>

            {/* PDF Button */}
            <div className={`flex ${isAr ? "justify-end" : "justify-start"}`}>
              <button onClick={handleDownloadPDF}
                className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl border border-white/15 text-white/70 text-sm font-medium hover:border-[#F5C518]/40 hover:text-white transition-colors">
                <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M12 10v6m0 0l-3-3m3 3l3-3M3 17V7a2 2 0 012-2h6l2 2h6a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2z" />
                </svg>
                {t.pdfBtn}
              </button>
            </div>

            {/* CTA */}
            <div className="bg-[#080E1A] border border-[#F5C518]/15 rounded-2xl p-6 md:p-8 text-center">
              <h2 className="text-white font-black text-xl md:text-2xl mb-2">{t.ctaHeading}</h2>
              <p className="text-white/55 text-sm mb-6 max-w-lg mx-auto">{t.ctaSub}</p>
              <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
                <a href="https://wa.me/966564229190" target="_blank" rel="noopener noreferrer"
                  onClick={() => trackEvent("audit_cta_click", { type: "whatsapp" })}
                  className="w-full sm:w-auto inline-flex items-center justify-center gap-2 px-7 py-3.5 rounded-full bg-[#F5C518] text-[#080E1A] font-bold text-sm hover:bg-[#F5C518]/90 transition-all shadow-xl shadow-[#F5C518]/20">
                  {t.ctaWa}
                </a>
                <a href="tel:+966564229190"
                  onClick={() => trackEvent("audit_cta_click", { type: "call" })}
                  className="w-full sm:w-auto inline-flex items-center justify-center gap-2 px-7 py-3.5 rounded-full border border-white/20 text-white font-medium text-sm hover:border-white/40 transition-all">
                  <span dir="ltr">{t.ctaCall}</span>
                </a>
              </div>
            </div>

          </div>
        </section>
      )}

      {/* SEO CONTENT */}
      <AuditPageSEO locale={locale} />
    </>
  );
}
