"use client";

import { useState, useRef, useEffect } from "react";
import { useParams } from "next/navigation";
import { trackEvent } from "@/lib/analytics";

type Locale = "en" | "ar";
type AuditStatus = "good" | "warning" | "critical";

interface AuditCategory {
  name: string;
  score: number;
  status: AuditStatus;
  findings: string[];
  recommendations: string[];
}

interface AuditResult {
  overallScore: number;
  categories: AuditCategory[];
  topPriorities: string[];
  summary: string;
}

const BUSINESS_TYPES = {
  en: ["Restaurant", "Clinic/Healthcare", "Salon/Beauty", "Real Estate", "Retail/E-commerce", "Education", "Automotive", "Hospitality", "Other"],
  ar: ["مطعم", "عيادة/رعاية صحية", "صالون/تجميل", "عقارات", "تجزئة/تجارة إلكترونية", "تعليم", "سيارات", "ضيافة", "أخرى"],
};

const LOADING_MESSAGES = {
  en: ["Analyzing website structure...", "Checking SEO elements...", "Evaluating mobile experience...", "Assessing content quality...", "Reviewing local SEO signals...", "Generating report..."],
  ar: ["تحليل هيكل الموقع...", "فحص عناصر SEO...", "تقييم تجربة الجوال...", "تقييم جودة المحتوى...", "مراجعة إشارات SEO المحلي...", "إنشاء التقرير..."],
};

const UI = {
  en: {
    badge: "AI-Powered",
    h1: "Free Website & Marketing Audit",
    sub: "Get an instant AI-powered analysis of your website's SEO, performance, mobile-friendliness, and digital marketing readiness — completely free.",
    form: {
      url: "Website URL", urlPlaceholder: "https://yourwebsite.com",
      name: "Full Name", namePlaceholder: "Your full name",
      email: "Email Address", emailPlaceholder: "you@company.com",
      phone: "Phone Number (optional)", phonePlaceholder: "+966 5X XXX XXXX",
      businessType: "Business Type",
      businessTypePlaceholder: "Select your business type",
      submit: "Run Free Audit →",
      submitting: "Analyzing...",
    },
    overallLabel: "Overall Website Health Score",
    priorities: "Your Top 3 Priorities",
    summaryLabel: "Executive Summary",
    ctaHeading: "Want us to fix these issues?",
    ctaSub: "Our team can implement all recommendations and grow your online presence.",
    ctaWa: "WhatsApp Us →",
    ctaCall: "Call +966 56 422 9190",
    pdfBtn: "Download PDF Report",
    tryAgain: "Try Again",
    errorLabel: "Analysis failed",
    errorSub: "Something went wrong during analysis. Please try again or contact us via WhatsApp.",
    findings: "Findings",
    recommendations: "Recommendations",
    statusGood: "Good ✓",
    statusWarning: "Warning ⚠",
    statusCritical: "Critical ✗",
    printTitle: "Website Audit Report",
    printDate: "Report Date",
    printUrl: "Audited Website",
    printFooter: "Report generated by Local City Solutions | localcitysolutions.com | +966 56 422 9190 | hello@localcitysolutions.com",
  },
  ar: {
    badge: "بالذكاء الاصطناعي",
    h1: "تدقيق مجاني لموقعك الإلكتروني",
    sub: "احصل على تحليل فوري بالذكاء الاصطناعي لموقعك — SEO، الأداء، التوافق مع الجوال، وجاهزية التسويق الرقمي — مجاناً بالكامل.",
    form: {
      url: "رابط الموقع", urlPlaceholder: "https://موقعك.com",
      name: "الاسم الكامل", namePlaceholder: "اسمك الكامل",
      email: "البريد الإلكتروني", emailPlaceholder: "you@company.com",
      phone: "رقم الجوال (اختياري)", phonePlaceholder: "+966 5X XXX XXXX",
      businessType: "نوع النشاط التجاري",
      businessTypePlaceholder: "اختر نوع نشاطك",
      submit: "ابدأ التدقيق المجاني ←",
      submitting: "جاري التحليل...",
    },
    overallLabel: "النتيجة الإجمالية لصحة الموقع",
    priorities: "أولوياتك الثلاث الأهم",
    summaryLabel: "الملخص",
    ctaHeading: "تبي نصلح هذي المشاكل؟",
    ctaSub: "فريقنا يقدر ينفذ كل التوصيات وينمي تواجدك الرقمي.",
    ctaWa: "واتساب ←",
    ctaCall: "اتصل +966 56 422 9190",
    pdfBtn: "تحميل التقرير PDF",
    tryAgain: "حاول مرة أخرى",
    errorLabel: "فشل التحليل",
    errorSub: "حدث خطأ أثناء التحليل. يرجى المحاولة مرة أخرى أو تواصل معنا عبر واتساب.",
    findings: "النتائج",
    recommendations: "التوصيات",
    statusGood: "جيد ✓",
    statusWarning: "تحذير ⚠",
    statusCritical: "حرج ✗",
    printTitle: "تقرير تدقيق الموقع الإلكتروني",
    printDate: "تاريخ التقرير",
    printUrl: "الموقع المُدقق",
    printFooter: "تقرير من لوكال سيتي سولوشنز | localcitysolutions.com | +966 56 422 9190 | hello@localcitysolutions.com",
  },
};

function ScoreRing({ score, size = 120, stroke = 8 }: { score: number; size?: number; stroke?: number }) {
  const [displayed, setDisplayed] = useState(0);
  const r = (size - stroke) / 2;
  const circ = 2 * Math.PI * r;
  const color = score >= 80 ? "#22c55e" : score >= 50 ? "#F5C518" : "#ef4444";

  useEffect(() => {
    let start: number | null = null;
    const duration = 1000;
    const step = (timestamp: number) => {
      if (!start) start = timestamp;
      const progress = Math.min((timestamp - start) / duration, 1);
      setDisplayed(Math.round(progress * score));
      if (progress < 1) requestAnimationFrame(step);
    };
    requestAnimationFrame(step);
  }, [score]);

  const offset = circ - (displayed / 100) * circ;

  return (
    <svg width={size} height={size} className="rotate-[-90deg]">
      <circle cx={size / 2} cy={size / 2} r={r} fill="none" stroke="rgba(255,255,255,0.08)" strokeWidth={stroke} />
      <circle
        cx={size / 2} cy={size / 2} r={r} fill="none"
        stroke={color} strokeWidth={stroke}
        strokeDasharray={circ} strokeDashoffset={offset}
        strokeLinecap="round"
        style={{ transition: "stroke-dashoffset 0.05s linear" }}
      />
      <text
        x={size / 2} y={size / 2 + 1}
        textAnchor="middle" dominantBaseline="middle"
        fill={color} fontSize={size * 0.22} fontWeight="800"
        style={{ transform: "rotate(90deg)", transformOrigin: `${size / 2}px ${size / 2}px` }}
      >
        {displayed}
      </text>
    </svg>
  );
}

function SmallScoreRing({ score }: { score: number }) {
  const [displayed, setDisplayed] = useState(0);
  const size = 48; const stroke = 5;
  const r = (size - stroke) / 2;
  const circ = 2 * Math.PI * r;
  const color = score >= 80 ? "#22c55e" : score >= 50 ? "#F5C518" : "#ef4444";

  useEffect(() => {
    let start: number | null = null;
    const step = (ts: number) => {
      if (!start) start = ts;
      const p = Math.min((ts - start) / 800, 1);
      setDisplayed(Math.round(p * score));
      if (p < 1) requestAnimationFrame(step);
    };
    requestAnimationFrame(step);
  }, [score]);

  const offset = circ - (displayed / 100) * circ;

  return (
    <svg width={size} height={size} className="rotate-[-90deg] shrink-0">
      <circle cx={size / 2} cy={size / 2} r={r} fill="none" stroke="rgba(255,255,255,0.08)" strokeWidth={stroke} />
      <circle cx={size / 2} cy={size / 2} r={r} fill="none" stroke={color} strokeWidth={stroke}
        strokeDasharray={circ} strokeDashoffset={offset} strokeLinecap="round"
        style={{ transition: "stroke-dashoffset 0.05s linear" }}
      />
      <text x={size / 2} y={size / 2 + 1} textAnchor="middle" dominantBaseline="middle"
        fill={color} fontSize={11} fontWeight="700"
        style={{ transform: "rotate(90deg)", transformOrigin: `${size / 2}px ${size / 2}px` }}
      >
        {displayed}
      </text>
    </svg>
  );
}

export default function FreeAuditPage() {
  const params = useParams();
  const locale = (params?.locale as Locale) || "en";
  const isAr = locale === "ar";
  const t = UI[locale] || UI.en;
  const bTypes = BUSINESS_TYPES[locale] || BUSINESS_TYPES.en;

  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [auditResult, setAuditResult] = useState<AuditResult | null>(null);
  const [error, setError] = useState("");
  const [loadingMessage, setLoadingMessage] = useState("");
  const [auditedUrl, setAuditedUrl] = useState("");

  const reportRef = useRef<HTMLDivElement>(null);
  const formRef = useRef<HTMLFormElement>(null);

  async function handleSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setIsAnalyzing(true);
    setError("");
    setAuditResult(null);

    const formData = new FormData(e.currentTarget);
    const websiteUrl = formData.get("url") as string;
    const businessType = formData.get("businessType") as string;
    setAuditedUrl(websiteUrl);

    // Fire-and-forget Web3Forms lead capture
    const w3 = new FormData();
    w3.append("access_key", "f3331300-e0d7-4572-9c9d-69ce21d88b26");
    w3.append("subject", "New Free Audit Lead — LCS");
    w3.append("from_name", "LCS Audit Tool");
    w3.append("name", formData.get("name") as string);
    w3.append("email", formData.get("email") as string);
    w3.append("phone", (formData.get("phone") as string) || "");
    w3.append("Website URL", websiteUrl);
    w3.append("Business Type", businessType);
    fetch("https://api.web3forms.com/submit", { method: "POST", body: w3 });

    // Track start
    trackEvent("audit_started", { url: websiteUrl, business_type: businessType });

    // Rotate loading messages
    const msgs = LOADING_MESSAGES[locale] || LOADING_MESSAGES.en;
    let msgIdx = 0;
    setLoadingMessage(msgs[0]);
    const msgInterval = setInterval(() => {
      msgIdx = (msgIdx + 1) % msgs.length;
      setLoadingMessage(msgs[msgIdx]);
    }, 2500);

    try {
      const siteRes = await fetch("/api/fetch-site", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url: websiteUrl }),
      });
      const siteData = siteRes.ok ? await siteRes.json() : null;

      const auditRes = await fetch("/api/audit", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url: websiteUrl, siteData, businessType }),
      });

      if (!auditRes.ok) throw new Error("Audit failed");

      const result: AuditResult = await auditRes.json();
      setAuditResult(result);
      trackEvent("audit_completed", { url: websiteUrl, score: result.overallScore });

      // Scroll to report
      setTimeout(() => {
        reportRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
      }, 100);
    } catch {
      setError(t.errorSub);
    } finally {
      clearInterval(msgInterval);
      setIsAnalyzing(false);
    }
  }

  function handlePrint() {
    if (!auditResult) return;
    trackEvent("audit_pdf_download", { url: auditedUrl, score: auditResult.overallScore });
    window.print();
  }

  const statusColor = (s: AuditStatus) =>
    s === "good" ? "text-green-400 bg-green-400/10 border-green-400/20"
    : s === "warning" ? "text-[#F5C518] bg-[#F5C518]/10 border-[#F5C518]/20"
    : "text-red-400 bg-red-400/10 border-red-400/20";

  const statusLabel = (s: AuditStatus) =>
    s === "good" ? t.statusGood : s === "warning" ? t.statusWarning : t.statusCritical;

  const today = new Date().toLocaleDateString(isAr ? "ar-SA" : "en-GB", {
    year: "numeric", month: "long", day: "numeric",
  });

  return (
    <>
      {/* Print stylesheet */}
      <style>{`
        @media print {
          body * { visibility: hidden !important; }
          #print-report, #print-report * { visibility: visible !important; }
          #print-report {
            position: fixed !important;
            left: 0 !important; top: 0 !important;
            width: 100% !important;
            background: white !important;
            color: #1a1a1a !important;
            padding: 40px !important;
            font-size: 12px !important;
            line-height: 1.6 !important;
            z-index: 99999 !important;
          }
        }
      `}</style>

      {/* Hidden print report */}
      {auditResult && (
        <div id="print-report" style={{ display: "none" }}>
          <div style={{ borderBottom: "3px solid #F5C518", paddingBottom: "16px", marginBottom: "24px" }}>
            <div style={{ fontSize: "22px", fontWeight: "900", color: "#0A1628" }}>Local City Solutions</div>
            <div style={{ fontSize: "16px", fontWeight: "700", marginTop: "4px" }}>{t.printTitle}</div>
          </div>
          <div style={{ marginBottom: "16px", fontSize: "13px", color: "#555" }}>
            <div><strong>{t.printDate}:</strong> {today}</div>
            <div><strong>{t.printUrl}:</strong> {auditedUrl}</div>
            <div><strong>{t.overallLabel}:</strong> {auditResult.overallScore}/100</div>
          </div>
          <div style={{ marginBottom: "24px" }}>
            <h2 style={{ fontSize: "15px", fontWeight: "700", borderLeft: "3px solid #F5C518", paddingLeft: "8px", marginBottom: "12px" }}>{t.summaryLabel}</h2>
            <p>{auditResult.summary}</p>
          </div>
          <div style={{ marginBottom: "24px" }}>
            <h2 style={{ fontSize: "15px", fontWeight: "700", borderLeft: "3px solid #F5C518", paddingLeft: "8px", marginBottom: "12px" }}>{t.priorities}</h2>
            {auditResult.topPriorities.map((p, i) => (
              <div key={i} style={{ marginBottom: "6px" }}><strong>{i + 1}.</strong> {p}</div>
            ))}
          </div>
          {auditResult.categories.map((cat) => (
            <div key={cat.name} style={{ marginBottom: "20px", pageBreakInside: "avoid" }}>
              <h2 style={{ fontSize: "14px", fontWeight: "700", borderLeft: "3px solid #F5C518", paddingLeft: "8px", marginBottom: "8px" }}>
                {cat.name} — {cat.score}/100 ({cat.status.toUpperCase()})
              </h2>
              <div style={{ marginLeft: "8px" }}>
                <strong>{t.findings}:</strong>
                <ul style={{ margin: "4px 0 8px 16px" }}>
                  {cat.findings.map((f, i) => <li key={i}>{f}</li>)}
                </ul>
                <strong>{t.recommendations}:</strong>
                <ul style={{ margin: "4px 0 0 16px" }}>
                  {cat.recommendations.map((r, i) => <li key={i}>{r}</li>)}
                </ul>
              </div>
            </div>
          ))}
          <div style={{ borderTop: "1px solid #ddd", marginTop: "32px", paddingTop: "12px", fontSize: "11px", color: "#888" }}>
            {t.printFooter}
          </div>
        </div>
      )}

      {/* HERO */}
      <section
        className="relative bg-[#080E1A] pt-28 md:pt-36 pb-16 overflow-hidden"
        dir={isAr ? "rtl" : "ltr"}
      >
        <div
          className="absolute inset-0 pointer-events-none"
          style={{ background: "radial-gradient(ellipse 70% 50% at 50% 0%, rgba(245,197,24,0.07) 0%, transparent 70%)" }}
        />
        <div className="relative max-w-3xl mx-auto px-4 sm:px-6 text-center">
          <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-[#F5C518]/25 bg-[#F5C518]/[0.08] text-[#F5C518] text-xs font-bold uppercase tracking-[0.15em] mb-5">
            <span className="w-1.5 h-1.5 rounded-full bg-[#F5C518] animate-pulse" />
            {t.badge}
          </span>
          <h1 className="text-3xl md:text-5xl font-black text-white mb-4 leading-tight">{t.h1}</h1>
          <p className="text-white/55 text-base md:text-lg max-w-2xl mx-auto">{t.sub}</p>
        </div>
      </section>

      {/* FORM */}
      <section
        className="bg-[#080E1A] pb-16 md:pb-20"
        dir={isAr ? "rtl" : "ltr"}
      >
        <div className="max-w-2xl mx-auto px-4 sm:px-6">
          <form
            ref={formRef}
            onSubmit={handleSubmit}
            className={`bg-[#0E1A2E] border border-white/[0.07] rounded-2xl p-6 md:p-8 space-y-5 transition-opacity ${isAnalyzing ? "opacity-60 pointer-events-none" : ""}`}
          >
            {/* Website URL */}
            <div>
              <label className="block text-white/70 text-sm font-medium mb-1.5">{t.form.url} <span className="text-[#F5C518]">*</span></label>
              <input
                type="url" name="url" required
                placeholder={t.form.urlPlaceholder}
                className="w-full bg-[#080E1A] border border-white/10 rounded-xl px-4 py-3 text-white placeholder-white/25 text-sm focus:outline-none focus:border-[#F5C518]/50 transition-colors"
              />
            </div>
            {/* Name + Email row */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-white/70 text-sm font-medium mb-1.5">{t.form.name} <span className="text-[#F5C518]">*</span></label>
                <input
                  type="text" name="name" required
                  placeholder={t.form.namePlaceholder}
                  className="w-full bg-[#080E1A] border border-white/10 rounded-xl px-4 py-3 text-white placeholder-white/25 text-sm focus:outline-none focus:border-[#F5C518]/50 transition-colors"
                />
              </div>
              <div>
                <label className="block text-white/70 text-sm font-medium mb-1.5">{t.form.email} <span className="text-[#F5C518]">*</span></label>
                <input
                  type="email" name="email" required
                  placeholder={t.form.emailPlaceholder}
                  className="w-full bg-[#080E1A] border border-white/10 rounded-xl px-4 py-3 text-white placeholder-white/25 text-sm focus:outline-none focus:border-[#F5C518]/50 transition-colors"
                />
              </div>
            </div>
            {/* Phone + Business type row */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-white/70 text-sm font-medium mb-1.5">{t.form.phone}</label>
                <input
                  type="tel" name="phone"
                  placeholder={t.form.phonePlaceholder}
                  className="w-full bg-[#080E1A] border border-white/10 rounded-xl px-4 py-3 text-white placeholder-white/25 text-sm focus:outline-none focus:border-[#F5C518]/50 transition-colors"
                />
              </div>
              <div>
                <label className="block text-white/70 text-sm font-medium mb-1.5">{t.form.businessType} <span className="text-[#F5C518]">*</span></label>
                <select
                  name="businessType" required
                  className="w-full bg-[#080E1A] border border-white/10 rounded-xl px-4 py-3 text-white text-sm focus:outline-none focus:border-[#F5C518]/50 transition-colors appearance-none"
                >
                  <option value="" disabled selected>{t.form.businessTypePlaceholder}</option>
                  {bTypes.map((bt) => <option key={bt} value={bt}>{bt}</option>)}
                </select>
              </div>
            </div>
            {/* Web3Forms hidden fields */}
            <input type="checkbox" name="botcheck" className="hidden" style={{ display: "none" }} />

            <button
              type="submit"
              disabled={isAnalyzing}
              className="w-full py-4 rounded-xl bg-[#F5C518] text-[#080E1A] font-bold text-base hover:bg-[#F5C518]/90 transition-all shadow-xl shadow-[#F5C518]/20 disabled:opacity-60 flex items-center justify-center gap-2"
            >
              {isAnalyzing ? (
                <>
                  <svg className="w-4 h-4 animate-spin" viewBox="0 0 24 24" fill="none">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z" />
                  </svg>
                  {t.form.submitting}
                </>
              ) : t.form.submit}
            </button>
          </form>

          {/* Loading state */}
          {isAnalyzing && (
            <div className="mt-6 text-center">
              <div className="w-full h-1.5 bg-white/[0.06] rounded-full overflow-hidden mb-4">
                <div
                  className="h-full bg-[#F5C518] rounded-full"
                  style={{ animation: "progress-pulse 2.5s ease-in-out infinite", width: "60%" }}
                />
              </div>
              <p className="text-white/50 text-sm">{loadingMessage}</p>
            </div>
          )}

          {/* Error state */}
          {error && !isAnalyzing && (
            <div className={`mt-6 p-4 rounded-xl border border-red-400/20 bg-red-400/[0.05] ${isAr ? "text-right" : ""}`}>
              <p className="text-red-400 font-semibold text-sm mb-1">{t.errorLabel}</p>
              <p className="text-white/60 text-sm mb-3">{error}</p>
              <div className="flex gap-3 flex-wrap">
                <button
                  onClick={() => { setError(""); setAuditResult(null); }}
                  className="text-sm px-4 py-2 rounded-lg border border-white/15 text-white/70 hover:border-white/30 transition-colors"
                >
                  {t.tryAgain}
                </button>
                <a
                  href="https://wa.me/966564229190"
                  target="_blank" rel="noopener noreferrer"
                  className="text-sm px-4 py-2 rounded-lg bg-[#25D366]/10 border border-[#25D366]/20 text-[#25D366] hover:bg-[#25D366]/20 transition-colors"
                >
                  WhatsApp
                </a>
              </div>
            </div>
          )}
        </div>
      </section>

      {/* AUDIT REPORT */}
      {auditResult && (
        <section
          ref={reportRef}
          className="bg-[#0C1424] py-12 md:py-16"
          dir={isAr ? "rtl" : "ltr"}
        >
          <div className="max-w-5xl mx-auto px-4 sm:px-6 space-y-10">

            {/* Overall Score */}
            <div className="flex flex-col items-center text-center">
              <ScoreRing score={auditResult.overallScore} size={140} stroke={10} />
              <p className="text-white/55 text-sm mt-3">{t.overallLabel}</p>
            </div>

            {/* Category Cards */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {auditResult.categories.map((cat) => (
                <div
                  key={cat.name}
                  className="bg-[#0E1A2E] border border-white/[0.07] rounded-xl p-5 hover:border-[#F5C518]/20 hover:-translate-y-0.5 transition-all"
                >
                  <div className="flex items-center justify-between mb-3">
                    <SmallScoreRing score={cat.score} />
                    <span className={`text-xs font-bold px-2.5 py-1 rounded-full border ${statusColor(cat.status)}`}>
                      {statusLabel(cat.status)}
                    </span>
                  </div>
                  <h3 className="text-white font-bold text-sm mb-3">{cat.name}</h3>

                  <details open>
                    <summary className="text-[#F5C518] text-xs font-semibold cursor-pointer mb-2 select-none">{t.findings}</summary>
                    <ul className="space-y-1.5 mb-3">
                      {cat.findings.map((f, i) => (
                        <li key={i} className="text-white/55 text-xs leading-relaxed flex gap-2">
                          <span className="text-white/20 shrink-0 mt-0.5">•</span>{f}
                        </li>
                      ))}
                    </ul>
                  </details>

                  <details open>
                    <summary className="text-[#F5C518] text-xs font-semibold cursor-pointer mb-2 select-none">{t.recommendations}</summary>
                    <ul className="space-y-1.5">
                      {cat.recommendations.map((r, i) => (
                        <li key={i} className="text-white/55 text-xs leading-relaxed flex gap-2">
                          <span className="text-[#F5C518]/50 shrink-0 mt-0.5">→</span>{r}
                        </li>
                      ))}
                    </ul>
                  </details>
                </div>
              ))}
            </div>

            {/* Top Priorities */}
            <div className={`border-l-[3px] border-l-[#F5C518]/60 ${isAr ? "border-l-0 border-r-[3px] border-r-[#F5C518]/60 pl-0 pr-5" : "pl-5"} bg-[#0E1A2E] rounded-r-xl py-5 pr-5`}>
              <h2 className="text-white font-bold text-lg mb-4">{t.priorities}</h2>
              <ol className="space-y-3">
                {auditResult.topPriorities.map((p, i) => (
                  <li key={i} className="flex gap-3 items-start">
                    <span className="w-6 h-6 rounded-full bg-[#F5C518]/10 border border-[#F5C518]/25 text-[#F5C518] text-xs font-bold flex items-center justify-center shrink-0 mt-0.5">
                      {i + 1}
                    </span>
                    <span className="text-white/75 text-sm leading-relaxed">{p}</span>
                  </li>
                ))}
              </ol>
            </div>

            {/* Summary */}
            <div className="bg-[#0E1A2E] border border-white/[0.07] rounded-xl p-6">
              <h2 className="text-white font-bold text-lg mb-3">{t.summaryLabel}</h2>
              <p className="text-white/60 text-sm leading-relaxed">{auditResult.summary}</p>
            </div>

            {/* PDF Button */}
            <div className={`flex ${isAr ? "justify-end" : "justify-start"}`}>
              <button
                onClick={handlePrint}
                className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl border border-white/15 text-white/70 text-sm font-medium hover:border-white/30 hover:text-white transition-colors"
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M12 10v6m0 0l-3-3m3 3l3-3M3 17V7a2 2 0 012-2h6l2 2h6a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2z" />
                </svg>
                {t.pdfBtn}
              </button>
            </div>

            {/* CTA */}
            <div className="bg-[#080E1A] border border-[#F5C518]/15 rounded-2xl p-6 md:p-8 text-center">
              <h2 className="text-white font-black text-xl md:text-2xl mb-2">{t.ctaHeading}</h2>
              <p className="text-white/55 text-sm mb-6 max-w-lg mx-auto">{t.ctaSub}</p>
              <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
                <a
                  href="https://wa.me/966564229190"
                  target="_blank" rel="noopener noreferrer"
                  onClick={() => trackEvent("audit_cta_click", { type: "whatsapp" })}
                  className="w-full sm:w-auto inline-flex items-center justify-center gap-2 px-7 py-3.5 rounded-full bg-[#F5C518] text-[#080E1A] font-bold text-sm hover:bg-[#F5C518]/90 transition-all shadow-xl shadow-[#F5C518]/20"
                >
                  {t.ctaWa}
                </a>
                <a
                  href="tel:+966564229190"
                  onClick={() => trackEvent("audit_cta_click", { type: "call" })}
                  className="w-full sm:w-auto inline-flex items-center justify-center gap-2 px-7 py-3.5 rounded-full border border-white/20 text-white font-medium text-sm hover:border-white/40 transition-all"
                >
                  <span dir="ltr">{t.ctaCall}</span>
                </a>
              </div>
            </div>
          </div>
        </section>
      )}

      {/* progress-pulse keyframe */}
      <style>{`
        @keyframes progress-pulse {
          0% { width: 5%; opacity: 0.8; }
          50% { width: 85%; opacity: 1; }
          100% { width: 5%; opacity: 0.8; }
        }
      `}</style>
    </>
  );
}

