// Client-safe: no "next/headers" or other server-only imports here. Client
// Components (e.g. LoginForm.tsx) import the dictionary directly from this
// file — importing it via lang.ts would pull `next/headers` into the client
// bundle and break the build.

export type ManageLang = "en" | "ar";

export const MANAGE_LANG_COOKIE = "manage-lang";

export const manageDict = {
  en: {
    appName: "Client Manager",
    nav: {
      dashboard: "Dashboard",
      clients: "Clients",
      payments: "Payments",
      reminders: "Reminders",
      team: "Team",
      signOut: "Sign out",
    },
    login: {
      title: "Sign in",
      email: "Email",
      password: "Password",
      submit: "Sign in",
      error: "Invalid email or password.",
    },
    dashboard: {
      title: "Dashboard",
      upcomingReminders: "Upcoming reminders",
      overduePayments: "Overdue payments",
      totalClients: "Total clients",
      noReminders: "No reminders due soon.",
      noOverdue: "No overdue payments.",
      viewAll: "View all",
    },
    clients: {
      title: "Clients",
      new: "New client",
      name: "Name",
      company: "Company",
      email: "Email",
      phone: "Phone",
      whatsapp: "WhatsApp",
      industry: "Industry",
      status: "Status",
      notes: "Notes",
      assignedTo: "Assigned to",
      unassigned: "Unassigned",
      save: "Save",
      delete: "Delete",
      search: "Search clients...",
      empty: "No clients yet.",
      statusLabels: { lead: "Lead", active: "Active", paused: "Paused", churned: "Churned" },
    },
    payments: {
      title: "Payments",
      new: "New payment",
      client: "Client",
      description: "Description",
      amount: "Amount",
      currency: "Currency",
      dueDate: "Due date",
      status: "Status",
      invoiceNumber: "Invoice #",
      markPaid: "Mark as paid",
      overdue: "Overdue",
      save: "Save",
      empty: "No payments yet.",
      statusLabels: { unpaid: "Unpaid", paid: "Paid" },
    },
    reminders: {
      title: "Reminders",
      new: "New reminder",
      client: "Client (optional)",
      reminderTitle: "Title",
      description: "Description",
      dueAt: "Due",
      channels: "Channels",
      markDone: "Mark done",
      dismiss: "Dismiss",
      save: "Save",
      empty: "No reminders yet.",
      channelLabels: { dashboard: "Dashboard", email: "Email", whatsapp: "WhatsApp" },
      statusLabels: { pending: "Pending", sent: "Sent", done: "Done", dismissed: "Dismissed" },
    },
    team: {
      title: "Team",
      role: "Role",
      active: "Active",
      makeAdmin: "Make admin",
      makeStaff: "Make staff",
      deactivate: "Deactivate",
      activate: "Activate",
      adminOnly: "Admins only.",
    },
    common: {
      cancel: "Cancel",
      edit: "Edit",
      back: "Back",
      loading: "Loading...",
      requiredField: "This field is required.",
      genericError: "Something went wrong. Please try again.",
    },
  },
  ar: {
    appName: "إدارة العملاء",
    nav: {
      dashboard: "لوحة التحكم",
      clients: "العملاء",
      payments: "المدفوعات",
      reminders: "التذكيرات",
      team: "الفريق",
      signOut: "تسجيل الخروج",
    },
    login: {
      title: "تسجيل الدخول",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      submit: "دخول",
      error: "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
    },
    dashboard: {
      title: "لوحة التحكم",
      upcomingReminders: "التذكيرات القادمة",
      overduePayments: "المدفوعات المتأخرة",
      totalClients: "إجمالي العملاء",
      noReminders: "لا توجد تذكيرات قريبة.",
      noOverdue: "لا توجد مدفوعات متأخرة.",
      viewAll: "عرض الكل",
    },
    clients: {
      title: "العملاء",
      new: "عميل جديد",
      name: "الاسم",
      company: "الشركة",
      email: "البريد الإلكتروني",
      phone: "الهاتف",
      whatsapp: "واتساب",
      industry: "المجال",
      status: "الحالة",
      notes: "ملاحظات",
      assignedTo: "المسؤول",
      unassigned: "غير مُسند",
      save: "حفظ",
      delete: "حذف",
      search: "بحث عن عميل...",
      empty: "لا يوجد عملاء بعد.",
      statusLabels: { lead: "عميل محتمل", active: "نشط", paused: "متوقف", churned: "منسحب" },
    },
    payments: {
      title: "المدفوعات",
      new: "دفعة جديدة",
      client: "العميل",
      description: "الوصف",
      amount: "المبلغ",
      currency: "العملة",
      dueDate: "تاريخ الاستحقاق",
      status: "الحالة",
      invoiceNumber: "رقم الفاتورة",
      markPaid: "تحديد كمدفوع",
      overdue: "متأخر",
      save: "حفظ",
      empty: "لا توجد مدفوعات بعد.",
      statusLabels: { unpaid: "غير مدفوع", paid: "مدفوع" },
    },
    reminders: {
      title: "التذكيرات",
      new: "تذكير جديد",
      client: "العميل (اختياري)",
      reminderTitle: "العنوان",
      description: "الوصف",
      dueAt: "الموعد",
      channels: "القنوات",
      markDone: "تحديد كمنجز",
      dismiss: "تجاهل",
      save: "حفظ",
      empty: "لا توجد تذكيرات بعد.",
      channelLabels: { dashboard: "لوحة التحكم", email: "البريد الإلكتروني", whatsapp: "واتساب" },
      statusLabels: { pending: "قيد الانتظار", sent: "أُرسل", done: "منجز", dismissed: "متجاهل" },
    },
    team: {
      title: "الفريق",
      role: "الدور",
      active: "نشط",
      makeAdmin: "ترقية لمشرف",
      makeStaff: "تنزيل لموظف",
      deactivate: "تعطيل",
      activate: "تفعيل",
      adminOnly: "للمشرفين فقط.",
    },
    common: {
      cancel: "إلغاء",
      edit: "تعديل",
      back: "رجوع",
      loading: "جاري التحميل...",
      requiredField: "هذا الحقل مطلوب.",
      genericError: "حدث خطأ ما. حاول مرة أخرى.",
    },
  },
} as const;

export function getDict(lang: ManageLang) {
  return manageDict[lang];
}
