// Client-safe: no "next/headers" or other server-only imports here. Client
// Components (e.g. LoginForm.tsx) import the dictionary directly from this
// file — importing it via lang.ts would pull `next/headers` into the client
// bundle and break the build.

export type ManageLang = "en" | "ar";

export const MANAGE_LANG_COOKIE = "manage-lang";

export const manageDict = {
  en: {
    appName: "Client Manager",
    nav: {
      dashboard: "Dashboard",
      clients: "Clients",
      payments: "Payments",
      reminders: "Reminders",
      team: "Team",
      quotations: "Quotations",
      settings: "Settings",
      signOut: "Sign out",
    },
    quotations: {
      title: "Quotations",
      new: "New quotation",
      quoteTitle: "Quotation title",
      quoteNumber: "Quote no.",
      client: "Client",
      issueDate: "Issue date",
      validUntil: "Valid until",
      currency: "Currency",
      vat: "Add 15% VAT",
      discount: "Discount",
      notes: "Notes (shown on the PDF)",
      terms: "Terms & conditions",
      items: "Line items",
      addItem: "Add line",
      removeItem: "Remove",
      description: "Description",
      kind: "Billing",
      quantity: "Qty",
      unitPrice: "Unit price",
      lineTotal: "Line total",
      subtotal: "One-off subtotal",
      vatAmount: "VAT (15%)",
      total: "Total due on acceptance",
      monthlyTotal: "Recurring monthly",
      monthlyHint:
        "Billed every month after acceptance — not included in the total above.",
      status: "Status",
      save: "Save quotation",
      empty: "No quotations yet.",
      pdf: "Quotation PDF",
      duplicate: "Duplicate",
      delete: "Delete",
      markSent: "Mark sent",
      markAccepted: "Mark accepted",
      markDeclined: "Mark declined",
      convert: "Convert to charges",
      convertHint:
        "Creates a charge for every one-off line, and sets the recurring lines as this client's monthly billing plan. The first month is charged straight away.",
      convertReplace: "Replace the existing monthly plan",
      convertedOn: "Converted on",
      lockedNotice:
        "This quotation has been accepted, so its lines are locked. Duplicate it to make changes.",
      statusLabels: {
        draft: "Draft",
        sent: "Sent",
        accepted: "Accepted",
        declined: "Declined",
        expired: "Expired",
        converted: "Converted",
      },
      kindLabels: { monthly: "Monthly", setup: "Setup fee", one_off: "One-off" },
    },
    documents: {
      invoice: "Invoice",
      receipt: "Receipt",
      statement: "Statement",
      statementHint: "PDF of everything this client still owes.",
      bulkInvoices: "All due invoices (PDF)",
      bulkOverdue: "Overdue only (PDF)",
      noneDue: "Nothing is due right now.",
    },
    settings: {
      title: "Company & invoice settings",
      intro: "These details appear on every invoice, receipt and statement PDF.",
      nameEn: "Company name (English)",
      nameAr: "Company name (Arabic)",
      vatNumber: "VAT registration number",
      vatHint: "Required for ZATCA tax invoices and the QR code.",
      crNumber: "Commercial registration (CR) no.",
      addressEn: "Address (English)",
      addressAr: "Address (Arabic)",
      phone: "Phone",
      email: "Email",
      website: "Website",
      bankName: "Bank name",
      iban: "IBAN",
      invoicePrefix: "Invoice number prefix",
      receiptPrefix: "Receipt number prefix",
      quotePrefix: "Quotation number prefix",
      quoteValidity: "Default quotation validity (days)",
      prefixHint: "Used as PREFIX-YEAR-00001. Changing it only affects new documents.",
      paymentTermsEn: "Payment terms / note (English)",
      paymentTermsAr: "Payment terms / note (Arabic)",
      save: "Save settings",
      saved: "Settings saved.",
      adminOnly: "Only admins can change these.",
    },
    login: {
      title: "Sign in",
      email: "Email",
      password: "Password",
      submit: "Sign in",
      error: "Invalid email or password.",
    },
    dashboard: {
      title: "Dashboard",
      upcomingReminders: "Upcoming reminders",
      overduePayments: "Overdue payments",
      totalClients: "Total clients",
      outstanding: "Outstanding",
      advanceHeld: "Advance held",
      noReminders: "No reminders due soon.",
      noOverdue: "No overdue payments.",
      viewAll: "View all",
    },
    clients: {
      title: "Clients",
      new: "New client",
      name: "Name",
      company: "Business name",
      email: "Email",
      phone: "Phone",
      whatsapp: "WhatsApp",
      industry: "Industry",
      status: "Status",
      website: "Website",
      startDate: "Start date",
      primaryService: "Primary service",
      gmbName: "GMB name",
      gmbLocation: "GMB location",
      gmbLink: "GMB link",
      vatNumber: "VAT number",
      notes: "Notes",
      assignedTo: "Assigned to",
      unassigned: "Unassigned",
      selectService: "Select a service",
      save: "Save",
      delete: "Delete",
      search: "Search clients...",
      empty: "No clients yet.",
      statusLabels: { lead: "Lead", active: "Active", paused: "Paused", churned: "Churned" },
      serviceLabels: {
        seo: "SEO",
        local_seo_gmb: "Local SEO / GMB",
        web_design: "Web Design",
        web_development: "Web Development",
        google_ads_ppc: "Google Ads / PPC",
        social_media: "Social Media",
        content_blogs: "Content / Blogs",
        google_ads_fee: "Google Ads Fee",
        gmb_creation_fee: "GMB Creation Fee",
      },
    },
    services: {
      title: "Services",
      add: "Add service",
      service: "Service",
      status: "Status",
      startedAt: "Started",
      endedAt: "Ended",
      notes: "Notes",
      empty: "No services logged yet.",
      current: "Current",
      past: "Past",
      statusLabels: { active: "Active", completed: "Completed", paused: "Paused" },
      markActive: "Set active",
      markPaused: "Pause",
      markCompleted: "Complete",
      delete: "Remove",
    },
    payments: {
      title: "Charges",
      new: "New charge",
      client: "Client",
      description: "Description",
      amount: "Amount",
      currency: "Currency",
      dueDate: "Due date",
      status: "Status",
      kind: "Type",
      period: "Month billed",
      periodHint: "Only for monthly charges. One charge per client per month.",
      invoiceNumber: "Invoice #",
      markPaid: "Mark fully paid",
      overdue: "Overdue",
      save: "Save",
      empty: "No charges yet.",
      subtotal: "Subtotal",
      vat: "Add 15% VAT",
      vatAmount: "VAT (15%)",
      total: "Total",
      received: "Received",
      balance: "Balance",
      generate: "Generate due charges",
      generateHint: "Creates any monthly and setup charges that are due. Safe to run twice.",
      generated: "charge(s) created",
      upToDate: "Everything is already generated.",
      statusLabels: { unpaid: "Unpaid", partial: "Partly paid", paid: "Paid" },
      kindLabels: { monthly: "Monthly", setup: "Setup fee", one_off: "One-off" },
    },
    billing: {
      title: "Billing plan",
      none: "No billing plan yet — add one to bill this client automatically every month.",
      monthlyAmount: "Monthly amount",
      setupFee: "Setup / first-time fee",
      setupFeeHint: "Billed once when the plan starts (e.g. GMB creation).",
      setupFeeCharged: "Setup fee has already been charged.",
      billingDay: "Bill on day of month",
      billingDayHint: "1–28, so it works in every month.",
      startDate: "Plan starts",
      endDate: "Plan ends (optional)",
      vatEnabled: "Add 15% VAT to charges from this plan",
      status: "Plan status",
      statusLabels: { active: "Active", paused: "Paused", ended: "Ended" },
      save: "Save plan",
      perMonth: "/month",
      outstanding: "Outstanding",
      credit: "Advance / credit",
      totalCharged: "Total billed",
      totalReceived: "Total received",
      creditHint: "Paid in advance — applied automatically to the next charge.",
    },
    receipts: {
      title: "Payments received",
      record: "Record a payment",
      amount: "Amount received",
      receivedAt: "Date received",
      method: "Method",
      reference: "Reference / transaction #",
      notes: "Notes",
      applyTo: "Apply to",
      applyAuto: "Oldest unpaid charge first (recommended)",
      applyCredit: "Hold as advance / credit",
      unapplied: "unapplied",
      empty: "No payments recorded yet.",
      delete: "Delete",
      save: "Save payment",
      methodLabels: {
        bank: "Bank transfer",
        cash: "Cash",
        stc_pay: "STC Pay",
        card: "Card",
        cheque: "Cheque",
        other: "Other",
      },
    },
    reminders: {
      title: "Reminders",
      new: "New reminder",
      client: "Client (optional)",
      reminderTitle: "Title",
      description: "Description",
      dueAt: "Due",
      channels: "Channels",
      markDone: "Mark done",
      dismiss: "Dismiss",
      save: "Save",
      empty: "No reminders yet.",
      channelLabels: { dashboard: "Dashboard", email: "Email", whatsapp: "WhatsApp" },
      statusLabels: { pending: "Pending", sent: "Sent", done: "Done", dismissed: "Dismissed" },
    },
    team: {
      title: "Team",
      role: "Role",
      active: "Active",
      makeAdmin: "Make admin",
      makeStaff: "Make staff",
      deactivate: "Deactivate",
      activate: "Activate",
      adminOnly: "Admins only.",
    },
    common: {
      cancel: "Cancel",
      edit: "Edit",
      back: "Back",
      loading: "Loading...",
      requiredField: "This field is required.",
      genericError: "Something went wrong. Please try again.",
    },
  },
  ar: {
    appName: "إدارة العملاء",
    nav: {
      dashboard: "لوحة التحكم",
      clients: "العملاء",
      payments: "المدفوعات",
      reminders: "التذكيرات",
      team: "الفريق",
      quotations: "عروض الأسعار",
      settings: "الإعدادات",
      signOut: "تسجيل الخروج",
    },
    quotations: {
      title: "عروض الأسعار",
      new: "عرض سعر جديد",
      quoteTitle: "عنوان العرض",
      quoteNumber: "رقم العرض",
      client: "العميل",
      issueDate: "تاريخ الإصدار",
      validUntil: "صالح حتى",
      currency: "العملة",
      vat: "إضافة ضريبة 15%",
      discount: "الخصم",
      notes: "ملاحظات (تظهر في ملف PDF)",
      terms: "الشروط والأحكام",
      items: "البنود",
      addItem: "إضافة بند",
      removeItem: "حذف",
      description: "الوصف",
      kind: "نوع الفوترة",
      quantity: "الكمية",
      unitPrice: "سعر الوحدة",
      lineTotal: "إجمالي البند",
      subtotal: "المجموع لمرة واحدة",
      vatAmount: "الضريبة (15%)",
      total: "المستحق عند القبول",
      monthlyTotal: "الاشتراك الشهري",
      monthlyHint: "يُحتسب شهرياً بعد القبول — غير مشمول في الإجمالي أعلاه.",
      status: "الحالة",
      save: "حفظ العرض",
      empty: "لا توجد عروض أسعار بعد.",
      pdf: "ملف العرض PDF",
      duplicate: "نسخة جديدة",
      delete: "حذف",
      markSent: "تحديد كمُرسل",
      markAccepted: "تحديد كمقبول",
      markDeclined: "تحديد كمرفوض",
      convert: "تحويل إلى رسوم",
      convertHint:
        "يُنشئ رسماً لكل بند لمرة واحدة، ويضبط البنود الشهرية كخطة فوترة لهذا العميل. الشهر الأول يُحتسب فوراً.",
      convertReplace: "استبدال خطة الفوترة الحالية",
      convertedOn: "تاريخ التحويل",
      lockedNotice: "تم قبول هذا العرض، لذا لا يمكن تعديل بنوده. أنشئ نسخة جديدة للتعديل.",
      statusLabels: {
        draft: "مسودة",
        sent: "مُرسل",
        accepted: "مقبول",
        declined: "مرفوض",
        expired: "منتهي",
        converted: "محوَّل",
      },
      kindLabels: { monthly: "شهري", setup: "رسوم تأسيس", one_off: "مرة واحدة" },
    },
    documents: {
      invoice: "فاتورة",
      receipt: "سند قبض",
      statement: "كشف حساب",
      statementHint: "ملف PDF بكل المبالغ المستحقة على هذا العميل.",
      bulkInvoices: "كل الفواتير المستحقة (PDF)",
      bulkOverdue: "المتأخرة فقط (PDF)",
      noneDue: "لا توجد مبالغ مستحقة حالياً.",
    },
    settings: {
      title: "إعدادات الشركة والفواتير",
      intro: "تظهر هذه البيانات في كل فاتورة وسند قبض وكشف حساب.",
      nameEn: "اسم الشركة (إنجليزي)",
      nameAr: "اسم الشركة (عربي)",
      vatNumber: "الرقم الضريبي",
      vatHint: "مطلوب للفواتير الضريبية ورمز QR الخاص بهيئة الزكاة والضريبة.",
      crNumber: "رقم السجل التجاري",
      addressEn: "العنوان (إنجليزي)",
      addressAr: "العنوان (عربي)",
      phone: "الهاتف",
      email: "البريد الإلكتروني",
      website: "الموقع الإلكتروني",
      bankName: "اسم البنك",
      iban: "رقم الآيبان",
      invoicePrefix: "بادئة رقم الفاتورة",
      receiptPrefix: "بادئة رقم السند",
      quotePrefix: "بادئة رقم عرض السعر",
      quoteValidity: "مدة صلاحية عرض السعر (أيام)",
      prefixHint: "تُستخدم بصيغة PREFIX-YEAR-00001. التغيير يؤثر على المستندات الجديدة فقط.",
      paymentTermsEn: "شروط السداد / ملاحظة (إنجليزي)",
      paymentTermsAr: "شروط السداد / ملاحظة (عربي)",
      save: "حفظ الإعدادات",
      saved: "تم حفظ الإعدادات.",
      adminOnly: "التعديل متاح للمشرفين فقط.",
    },
    login: {
      title: "تسجيل الدخول",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      submit: "دخول",
      error: "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
    },
    dashboard: {
      title: "لوحة التحكم",
      upcomingReminders: "التذكيرات القادمة",
      overduePayments: "المدفوعات المتأخرة",
      totalClients: "إجمالي العملاء",
      outstanding: "المستحق",
      advanceHeld: "رصيد مقدم",
      noReminders: "لا توجد تذكيرات قريبة.",
      noOverdue: "لا توجد مدفوعات متأخرة.",
      viewAll: "عرض الكل",
    },
    clients: {
      title: "العملاء",
      new: "عميل جديد",
      name: "الاسم",
      company: "اسم النشاط التجاري",
      email: "البريد الإلكتروني",
      phone: "الهاتف",
      whatsapp: "واتساب",
      industry: "المجال",
      status: "الحالة",
      website: "الموقع الإلكتروني",
      startDate: "تاريخ البدء",
      primaryService: "الخدمة الأساسية",
      gmbName: "اسم النشاط على Google",
      gmbLocation: "موقع النشاط على Google",
      gmbLink: "رابط النشاط على Google",
      vatNumber: "الرقم الضريبي",
      notes: "ملاحظات",
      assignedTo: "المسؤول",
      unassigned: "غير مُسند",
      selectService: "اختر خدمة",
      save: "حفظ",
      delete: "حذف",
      search: "بحث عن عميل...",
      empty: "لا يوجد عملاء بعد.",
      statusLabels: { lead: "عميل محتمل", active: "نشط", paused: "متوقف", churned: "منسحب" },
      serviceLabels: {
        seo: "تحسين محركات البحث",
        local_seo_gmb: "SEO محلي / نشاط Google",
        web_design: "تصميم المواقع",
        web_development: "تطوير المواقع",
        google_ads_ppc: "إعلانات Google / الدفع بالنقرة",
        social_media: "وسائل التواصل الاجتماعي",
        content_blogs: "المحتوى / المدونات",
        google_ads_fee: "رسوم إعلانات Google",
        gmb_creation_fee: "رسوم إنشاء نشاط Google",
      },
    },
    services: {
      title: "الخدمات",
      add: "إضافة خدمة",
      service: "الخدمة",
      status: "الحالة",
      startedAt: "تاريخ البدء",
      endedAt: "تاريخ الانتهاء",
      notes: "ملاحظات",
      empty: "لا توجد خدمات مسجلة بعد.",
      current: "الحالية",
      past: "السابقة",
      statusLabels: { active: "نشطة", completed: "مكتملة", paused: "متوقفة" },
      markActive: "تفعيل",
      markPaused: "إيقاف",
      markCompleted: "إكمال",
      delete: "إزالة",
    },
    payments: {
      title: "الرسوم",
      new: "رسم جديد",
      client: "العميل",
      description: "الوصف",
      amount: "المبلغ",
      currency: "العملة",
      dueDate: "تاريخ الاستحقاق",
      status: "الحالة",
      kind: "النوع",
      period: "الشهر المُحاسب عليه",
      periodHint: "للرسوم الشهرية فقط. رسم واحد لكل عميل في الشهر.",
      invoiceNumber: "رقم الفاتورة",
      markPaid: "تحديد كمدفوع بالكامل",
      overdue: "متأخر",
      save: "حفظ",
      empty: "لا توجد رسوم بعد.",
      subtotal: "المجموع الفرعي",
      vat: "إضافة ضريبة 15%",
      vatAmount: "الضريبة (15%)",
      total: "الإجمالي",
      received: "المستلم",
      balance: "المتبقي",
      generate: "إنشاء الرسوم المستحقة",
      generateHint: "ينشئ الرسوم الشهرية ورسوم التأسيس المستحقة. يمكن تشغيله أكثر من مرة بأمان.",
      generated: "رسم/رسوم تم إنشاؤها",
      upToDate: "كل الرسوم منشأة بالفعل.",
      statusLabels: { unpaid: "غير مدفوع", partial: "مدفوع جزئياً", paid: "مدفوع" },
      kindLabels: { monthly: "شهري", setup: "رسوم تأسيس", one_off: "مرة واحدة" },
    },
    billing: {
      title: "خطة الفوترة",
      none: "لا توجد خطة فوترة بعد — أضف واحدة لفوترة هذا العميل شهرياً بشكل تلقائي.",
      monthlyAmount: "المبلغ الشهري",
      setupFee: "رسوم التأسيس / أول مرة",
      setupFeeHint: "تُحتسب مرة واحدة عند بدء الخطة (مثل إنشاء نشاط Google).",
      setupFeeCharged: "تم احتساب رسوم التأسيس بالفعل.",
      billingDay: "يوم الفوترة من الشهر",
      billingDayHint: "من 1 إلى 28 حتى تعمل في كل الأشهر.",
      startDate: "بداية الخطة",
      endDate: "نهاية الخطة (اختياري)",
      vatEnabled: "إضافة ضريبة 15% على رسوم هذه الخطة",
      status: "حالة الخطة",
      statusLabels: { active: "نشطة", paused: "متوقفة", ended: "منتهية" },
      save: "حفظ الخطة",
      perMonth: "/شهرياً",
      outstanding: "المستحق",
      credit: "رصيد مقدم",
      totalCharged: "إجمالي الفوترة",
      totalReceived: "إجمالي المستلم",
      creditHint: "مدفوع مقدماً — يُطبَّق تلقائياً على الرسم التالي.",
    },
    receipts: {
      title: "الدفعات المستلمة",
      record: "تسجيل دفعة",
      amount: "المبلغ المستلم",
      receivedAt: "تاريخ الاستلام",
      method: "طريقة الدفع",
      reference: "المرجع / رقم العملية",
      notes: "ملاحظات",
      applyTo: "تطبيق على",
      applyAuto: "أقدم رسم غير مدفوع أولاً (موصى به)",
      applyCredit: "الاحتفاظ به كرصيد مقدم",
      unapplied: "غير مطبَّق",
      empty: "لا توجد دفعات مسجلة بعد.",
      delete: "حذف",
      save: "حفظ الدفعة",
      methodLabels: {
        bank: "تحويل بنكي",
        cash: "نقداً",
        stc_pay: "STC Pay",
        card: "بطاقة",
        cheque: "شيك",
        other: "أخرى",
      },
    },
    reminders: {
      title: "التذكيرات",
      new: "تذكير جديد",
      client: "العميل (اختياري)",
      reminderTitle: "العنوان",
      description: "الوصف",
      dueAt: "الموعد",
      channels: "القنوات",
      markDone: "تحديد كمنجز",
      dismiss: "تجاهل",
      save: "حفظ",
      empty: "لا توجد تذكيرات بعد.",
      channelLabels: { dashboard: "لوحة التحكم", email: "البريد الإلكتروني", whatsapp: "واتساب" },
      statusLabels: { pending: "قيد الانتظار", sent: "أُرسل", done: "منجز", dismissed: "متجاهل" },
    },
    team: {
      title: "الفريق",
      role: "الدور",
      active: "نشط",
      makeAdmin: "ترقية لمشرف",
      makeStaff: "تنزيل لموظف",
      deactivate: "تعطيل",
      activate: "تفعيل",
      adminOnly: "للمشرفين فقط.",
    },
    common: {
      cancel: "إلغاء",
      edit: "تعديل",
      back: "رجوع",
      loading: "جاري التحميل...",
      requiredField: "هذا الحقل مطلوب.",
      genericError: "حدث خطأ ما. حاول مرة أخرى.",
    },
  },
} as const;

export function getDict(lang: ManageLang) {
  return manageDict[lang];
}
