// Client-safe: no "next/headers" or other server-only imports here. Client
// Components (e.g. LoginForm.tsx) import the dictionary directly from this
// file — importing it via lang.ts would pull `next/headers` into the client
// bundle and break the build.

export type ManageLang = "en" | "ar";

export const MANAGE_LANG_COOKIE = "manage-lang";

export const manageDict = {
  en: {
    appName: "Client Manager",
    nav: {
      dashboard: "Dashboard",
      clients: "Clients",
      payments: "Payments",
      reminders: "Reminders",
      team: "Team",
      quotations: "Quotations",
      partners: "Partners",
      settings: "Settings",
      signOut: "Sign out",
    },
    partners: {
      title: "Partners",
      intro:
        "Who is holding the business's money, and what the partners owe each other. Every payment received, every expense paid and every transfer between you is one line here.",
      adminOnly: "Only admins can see the partner ledger.",
      owes: "owes",
      settled: "All square — nobody owes anything.",
      balanceHint:
        "Fee revenue is split by share. Ad budget is client money: whoever holds it owes it to whoever spends it. Transfers between partners settle the difference.",
      received: "Received into account",
      expensesPaid: "Expenses paid",
      transfersOut: "Paid to partner",
      transfersIn: "Received from partner",
      holding: "Net cash held",
      fairShare: "Fair share",
      balance: "Balance",
      share: "Share",
      business: "Business totals",
      totalReceived: "Total received",
      adBudgetReceived: "Ad budget received (client money)",
      totalExpenses: "Total expenses",
      adSpend: "Ad spend paid",
      profit: "Profit (fees − shared costs)",
      unspentAdBudget: "Unspent ad budget",
      netCash: "Net cash in the business",
      recordTransfer: "Record a transfer (lain dain)",
      from: "From",
      to: "To",
      transferKind: "Type",
      transferKinds: {
        settlement: "Settling a share",
        personal: "Personal give / take",
        other: "Other",
      },
      recordExpense: "Record an expense",
      paidBy: "Paid by",
      category: "Category",
      categories: {
        ad_spend: "Ad spend (for a client)",
        tools: "Tools & software",
        subscriptions: "Subscriptions",
        salary: "Salaries / freelancers",
        office: "Office",
        other: "Other",
      },
      client: "Client (optional)",
      noClient: "Not for a specific client",
      description: "Description",
      date: "Date",
      amount: "Amount",
      ledger: "Ledger",
      effect: "Effect",
      entryReceipt: "Payment received",
      entryExpense: "Expense",
      entryTransfer: "Transfer",
      into: "into",
      settings: "Partner settings",
      settingsHint:
        "Names and profit shares. Shares must add up to 100%. The default account is pre-selected when recording a payment.",
      name: "Name",
      sharePercent: "Share %",
      defaultAccount: "Default receiving account",
      saveSettings: "Save partners",
      sharesMustTotal: "Shares must add up to 100%.",
      saved: "Saved.",
      save: "Save",
      delete: "Delete",
      confirmDelete: "Delete this entry? The balance between partners will change.",
      empty: "No entries yet.",
      receivedIn: "Received in",
      adsTitle: "Ads",
      adBudgetBilled: "Ad budget billed",
      adBudgetPaid: "Ad budget received",
      adSpendForClient: "Ad spend paid out",
      adsHint: "Client money for ads. Received − spent = what we still hold for them.",
    },
    quotations: {
      title: "Quotations",
      new: "New quotation",
      quoteTitle: "Quotation title",
      quoteNumber: "Quote no.",
      client: "Client",
      issueDate: "Issue date",
      validUntil: "Valid until",
      currency: "Currency",
      vat: "Add 15% VAT",
      discount: "Discount",
      notes: "Notes (shown on the PDF)",
      terms: "Terms & conditions",
      items: "Line items",
      addItem: "Add line",
      removeItem: "Remove",
      description: "Description",
      kind: "Billing",
      quantity: "Qty",
      unitPrice: "Unit price",
      lineTotal: "Line total",
      subtotal: "One-off subtotal",
      vatAmount: "VAT (15%)",
      total: "Total due on acceptance",
      monthlyTotal: "Recurring monthly",
      monthlyHint:
        "Billed every month after acceptance — not included in the total above.",
      status: "Status",
      save: "Save quotation",
      empty: "No quotations yet.",
      pdf: "Quotation PDF",
      duplicate: "Duplicate",
      delete: "Delete",
      markSent: "Mark sent",
      markAccepted: "Mark accepted",
      markDeclined: "Mark declined",
      convert: "Convert to charges",
      convertHint:
        "Creates a charge for every one-off line, and sets the recurring lines as this client's monthly billing plan. The first month is charged straight away.",
      convertReplace: "Replace the existing monthly plan",
      convertedOn: "Converted on",
      lockedNotice:
        "This quotation has been accepted, so its lines are locked. Duplicate it to make changes.",
      statusLabels: {
        draft: "Draft",
        sent: "Sent",
        accepted: "Accepted",
        declined: "Declined",
        expired: "Expired",
        converted: "Converted",
      },
      kindLabels: { monthly: "Monthly", setup: "Setup fee", one_off: "One-off" },
    },
    documents: {
      invoice: "Invoice",
      receipt: "Receipt",
      statement: "Statement",
      statementHint: "PDF of everything this client still owes.",
      bulkInvoices: "All due invoices (PDF)",
      bulkOverdue: "Overdue only (PDF)",
      noneDue: "Nothing is due right now.",
    },
    settings: {
      title: "Company & invoice settings",
      intro: "These details appear on every invoice, receipt and statement PDF.",
      nameEn: "Company name (English)",
      nameAr: "Company name (Arabic)",
      vatNumber: "VAT registration number",
      vatHint: "Required for ZATCA tax invoices and the QR code.",
      crNumber: "Commercial registration (CR) no.",
      addressEn: "Address (English)",
      addressAr: "Address (Arabic)",
      phone: "Phone",
      email: "Email",
      website: "Website",
      bankName: "Bank name",
      iban: "IBAN",
      invoicePrefix: "Invoice number prefix",
      receiptPrefix: "Receipt number prefix",
      quotePrefix: "Quotation number prefix",
      quoteValidity: "Default quotation validity (days)",
      prefixHint: "Used as PREFIX-YEAR-00001. Changing it only affects new documents.",
      paymentTermsEn: "Payment terms / note (English)",
      paymentTermsAr: "Payment terms / note (Arabic)",
      save: "Save settings",
      saved: "Settings saved.",
      adminOnly: "Only admins can change these.",
    },
    login: {
      title: "Sign in",
      email: "Email",
      password: "Password",
      submit: "Sign in",
      error: "Invalid email or password.",
    },
    dashboard: {
      title: "Dashboard",
      upcomingReminders: "Upcoming reminders",
      overduePayments: "Overdue payments",
      totalClients: "Total clients",
      outstanding: "Outstanding",
      advanceHeld: "Advance held",
      noReminders: "No reminders due soon.",
      noOverdue: "No overdue payments.",
      viewAll: "View all",
    },
    clients: {
      title: "Clients",
      new: "New client",
      name: "Name",
      company: "Business name",
      email: "Email",
      phone: "Phone",
      whatsapp: "WhatsApp",
      industry: "Industry",
      status: "Status",
      website: "Website",
      startDate: "Start date",
      primaryService: "Primary service",
      gmbName: "GMB name",
      gmbLocation: "GMB location",
      gmbLink: "GMB link",
      vatNumber: "VAT number",
      notes: "Notes",
      assignedTo: "Assigned to",
      unassigned: "Unassigned",
      selectService: "Select a service",
      save: "Save",
      delete: "Delete",
      confirmDelete:
        "Delete this client and ALL their services, charges, receipts and quotations? This cannot be undone.",
      search: "Search name, company, email, phone...",
      searchButton: "Search",
      empty: "No clients yet.",
      emptyFiltered: "No clients match these filters.",
      tags: "Tags",
      tagsHint: "Comma-separated — e.g. VIP, Riyadh, referral",
      allStatuses: "All statuses",
      allServices: "All services",
      anyStaff: "Any staff",
      noStaff: "Unassigned only",
      allTags: "All tags",
      sortNewest: "Newest first",
      sortOldest: "Oldest first",
      sortName: "Name A–Z",
      reset: "Reset",
      exportCsv: "Export CSV",
      contact: "Contact",
      outstanding: "Outstanding",
      added: "Added",
      pageLabel: "Page",
      of: "of",
      prev: "Previous",
      next: "Next",
      statsTotal: "Total clients",
      statsOutstanding: "Total outstanding",
      statsOverdue: "With overdue balance",
      statusLabels: { lead: "Lead", active: "Active", paused: "Paused", churned: "Churned" },
      serviceLabels: {
        seo: "SEO",
        local_seo_gmb: "Local SEO / GMB",
        web_design: "Web Design",
        web_development: "Web Development",
        google_ads_ppc: "Google Ads / PPC",
        social_media: "Social Media",
        content_blogs: "Content / Blogs",
        google_ads_fee: "Google Ads Fee",
        gmb_creation_fee: "GMB Creation Fee",
      },
    },
    services: {
      title: "Services",
      add: "Add service",
      service: "Service",
      status: "Status",
      startedAt: "Started",
      endedAt: "Ended",
      notes: "Notes",
      empty: "No services logged yet.",
      current: "Current",
      past: "Past",
      statusLabels: { active: "Active", completed: "Completed", paused: "Paused" },
      markActive: "Set active",
      markPaused: "Pause",
      markCompleted: "Complete",
      delete: "Remove",
      confirmDelete: "Remove this service entry?",
    },
    clientNotes: {
      title: "Notes log",
      placeholder: "Write a note — call summary, decision, next step...",
      save: "Add note",
      pin: "Pin",
      unpin: "Unpin",
      delete: "Delete",
      empty: "No notes yet.",
      confirmDelete: "Delete this note?",
    },
    activity: {
      title: "Activity",
      empty: "No activity recorded yet.",
      kindLabels: {
        client_created: "Client created",
        client_updated: "Details updated",
        status_changed: "Status changed",
        service_added: "Service added",
        service_status: "Service status changed",
        service_removed: "Service removed",
        plan_created: "Billing plan created",
        plan_updated: "Billing plan updated",
        charge_created: "Charge created",
        charge_deleted: "Charge deleted",
        payment_received: "Payment received",
        receipt_deleted: "Receipt deleted",
        quotation_created: "Quotation created",
        quotation_status: "Quotation status changed",
        expense_added: "Expense recorded",
        expense_deleted: "Expense deleted",
      },
    },
    payments: {
      title: "Charges",
      new: "New charge",
      client: "Client",
      description: "Description",
      amount: "Amount",
      currency: "Currency",
      dueDate: "Due date",
      status: "Status",
      kind: "Type",
      period: "Month billed",
      periodHint: "Only for monthly charges. One charge per client per month.",
      invoiceNumber: "Invoice #",
      markPaid: "Mark fully paid",
      confirmDelete: "Delete this charge?",
      overdue: "Overdue",
      save: "Save",
      empty: "No charges yet.",
      subtotal: "Subtotal",
      vat: "Add 15% VAT",
      vatAmount: "VAT (15%)",
      adBudget: "Ad budget — the client's money for ads, not our revenue",
      adBudgetShort: "Ad budget",
      total: "Total",
      received: "Received",
      balance: "Balance",
      generate: "Generate due charges",
      generateHint: "Creates any monthly and setup charges that are due. Safe to run twice.",
      generated: "charge(s) created",
      upToDate: "Everything is already generated.",
      statusLabels: { unpaid: "Unpaid", partial: "Partly paid", paid: "Paid" },
      kindLabels: { monthly: "Monthly", setup: "Setup fee", one_off: "One-off" },
    },
    billing: {
      title: "Billing plan",
      none: "No billing plan yet — add one to bill this client automatically every month.",
      monthlyAmount: "Monthly amount",
      adBudgetAmount: "Monthly ad budget",
      adBudgetHint: "Billed each month as a separate ad-budget charge, without VAT.",
      setupFee: "Setup / first-time fee",
      setupFeeHint: "Billed once when the plan starts (e.g. GMB creation).",
      setupFeeCharged: "Setup fee has already been charged.",
      billingDay: "Bill on day of month",
      billingDayHint: "1–28, so it works in every month.",
      startDate: "Plan starts",
      endDate: "Plan ends (optional)",
      vatEnabled: "Add 15% VAT to charges from this plan",
      status: "Plan status",
      statusLabels: { active: "Active", paused: "Paused", ended: "Ended" },
      save: "Save plan",
      perMonth: "/month",
      outstanding: "Outstanding",
      credit: "Advance / credit",
      totalCharged: "Total billed",
      totalReceived: "Total received",
      creditHint: "Paid in advance — applied automatically to the next charge.",
    },
    receipts: {
      title: "Payments received",
      record: "Record a payment",
      amount: "Amount received",
      receivedAt: "Date received",
      method: "Method",
      reference: "Reference / transaction #",
      notes: "Notes",
      applyTo: "Apply to",
      applyAuto: "Oldest unpaid charge first (recommended)",
      applyCredit: "Hold as advance / credit",
      unapplied: "unapplied",
      empty: "No payments recorded yet.",
      delete: "Delete",
      confirmDelete: "Delete this receipt? Its allocations to charges will be reversed.",
      save: "Save payment",
      methodLabels: {
        bank: "Bank transfer",
        cash: "Cash",
        stc_pay: "STC Pay",
        card: "Card",
        cheque: "Cheque",
        other: "Other",
      },
    },
    reminders: {
      title: "Reminders",
      new: "New reminder",
      client: "Client (optional)",
      reminderTitle: "Title",
      description: "Description",
      dueAt: "Due",
      channels: "Channels",
      markDone: "Mark done",
      dismiss: "Dismiss",
      save: "Save",
      empty: "No reminders yet.",
      channelLabels: { dashboard: "Dashboard", email: "Email", whatsapp: "WhatsApp" },
      statusLabels: { pending: "Pending", sent: "Sent", done: "Done", dismissed: "Dismissed" },
    },
    team: {
      title: "Team",
      role: "Role",
      active: "Active",
      makeAdmin: "Make admin",
      makeStaff: "Make staff",
      deactivate: "Deactivate",
      activate: "Activate",
      adminOnly: "Admins only.",
    },
    common: {
      cancel: "Cancel",
      edit: "Edit",
      back: "Back",
      loading: "Loading...",
      requiredField: "This field is required.",
      genericError: "Something went wrong. Please try again.",
    },
  },
  ar: {
    appName: "إدارة العملاء",
    nav: {
      dashboard: "لوحة التحكم",
      clients: "العملاء",
      payments: "المدفوعات",
      reminders: "التذكيرات",
      team: "الفريق",
      quotations: "عروض الأسعار",
      partners: "الشركاء",
      settings: "الإعدادات",
      signOut: "تسجيل الخروج",
    },
    partners: {
      title: "الشركاء",
      intro:
        "من يحتفظ بأموال الشركة، وما يدين به كل شريك للآخر. كل دفعة مستلمة وكل مصروف وكل تحويل بينكما يظهر هنا كسطر واحد.",
      adminOnly: "دفتر الشركاء متاح للمشرفين فقط.",
      owes: "مدين لـ",
      settled: "الحساب متساوٍ — لا أحد مدين لأحد.",
      balanceHint:
        "إيراد الأتعاب يُقسم حسب النسبة. ميزانية الإعلانات مال العميل: من يحتفظ بها مدين لمن ينفقها. التحويلات بين الشركاء تسوّي الفارق.",
      received: "المستلم في الحساب",
      expensesPaid: "المصروفات المدفوعة",
      transfersOut: "المدفوع للشريك",
      transfersIn: "المستلم من الشريك",
      holding: "صافي النقد المحتفظ به",
      fairShare: "الحصة العادلة",
      balance: "الرصيد",
      share: "النسبة",
      business: "إجماليات الشركة",
      totalReceived: "إجمالي المستلم",
      adBudgetReceived: "ميزانية إعلانات مستلمة (مال العميل)",
      totalExpenses: "إجمالي المصروفات",
      adSpend: "إنفاق إعلاني مدفوع",
      profit: "الربح (الأتعاب − التكاليف المشتركة)",
      unspentAdBudget: "ميزانية إعلانات غير منفقة",
      netCash: "صافي النقد في الشركة",
      recordTransfer: "تسجيل تحويل (لين دين)",
      from: "من",
      to: "إلى",
      transferKind: "النوع",
      transferKinds: {
        settlement: "تسوية حصة",
        personal: "أخذ / عطاء شخصي",
        other: "أخرى",
      },
      recordExpense: "تسجيل مصروف",
      paidBy: "دفعه",
      category: "الفئة",
      categories: {
        ad_spend: "إنفاق إعلاني (لعميل)",
        tools: "أدوات وبرامج",
        subscriptions: "اشتراكات",
        salary: "رواتب / مستقلون",
        office: "مكتب",
        other: "أخرى",
      },
      client: "العميل (اختياري)",
      noClient: "ليس لعميل محدد",
      description: "الوصف",
      date: "التاريخ",
      amount: "المبلغ",
      ledger: "الدفتر",
      effect: "الأثر",
      entryReceipt: "دفعة مستلمة",
      entryExpense: "مصروف",
      entryTransfer: "تحويل",
      into: "في حساب",
      settings: "إعدادات الشركاء",
      settingsHint:
        "الأسماء ونسب الأرباح. يجب أن يكون مجموع النسب 100%. الحساب الافتراضي يُختار مسبقاً عند تسجيل دفعة.",
      name: "الاسم",
      sharePercent: "النسبة %",
      defaultAccount: "حساب الاستلام الافتراضي",
      saveSettings: "حفظ الشركاء",
      sharesMustTotal: "يجب أن يكون مجموع النسب 100%.",
      saved: "تم الحفظ.",
      save: "حفظ",
      delete: "حذف",
      confirmDelete: "هل تريد حذف هذا السطر؟ سيتغير الرصيد بين الشركاء.",
      empty: "لا توجد سجلات بعد.",
      receivedIn: "استُلم في حساب",
      adsTitle: "الإعلانات",
      adBudgetBilled: "ميزانية إعلانات مُفوترة",
      adBudgetPaid: "ميزانية إعلانات مستلمة",
      adSpendForClient: "إنفاق إعلاني مدفوع",
      adsHint: "مال العميل للإعلانات. المستلم − المنفق = ما نحتفظ به له.",
    },
    quotations: {
      title: "عروض الأسعار",
      new: "عرض سعر جديد",
      quoteTitle: "عنوان العرض",
      quoteNumber: "رقم العرض",
      client: "العميل",
      issueDate: "تاريخ الإصدار",
      validUntil: "صالح حتى",
      currency: "العملة",
      vat: "إضافة ضريبة 15%",
      discount: "الخصم",
      notes: "ملاحظات (تظهر في ملف PDF)",
      terms: "الشروط والأحكام",
      items: "البنود",
      addItem: "إضافة بند",
      removeItem: "حذف",
      description: "الوصف",
      kind: "نوع الفوترة",
      quantity: "الكمية",
      unitPrice: "سعر الوحدة",
      lineTotal: "إجمالي البند",
      subtotal: "المجموع لمرة واحدة",
      vatAmount: "الضريبة (15%)",
      total: "المستحق عند القبول",
      monthlyTotal: "الاشتراك الشهري",
      monthlyHint: "يُحتسب شهرياً بعد القبول — غير مشمول في الإجمالي أعلاه.",
      status: "الحالة",
      save: "حفظ العرض",
      empty: "لا توجد عروض أسعار بعد.",
      pdf: "ملف العرض PDF",
      duplicate: "نسخة جديدة",
      delete: "حذف",
      markSent: "تحديد كمُرسل",
      markAccepted: "تحديد كمقبول",
      markDeclined: "تحديد كمرفوض",
      convert: "تحويل إلى رسوم",
      convertHint:
        "يُنشئ رسماً لكل بند لمرة واحدة، ويضبط البنود الشهرية كخطة فوترة لهذا العميل. الشهر الأول يُحتسب فوراً.",
      convertReplace: "استبدال خطة الفوترة الحالية",
      convertedOn: "تاريخ التحويل",
      lockedNotice: "تم قبول هذا العرض، لذا لا يمكن تعديل بنوده. أنشئ نسخة جديدة للتعديل.",
      statusLabels: {
        draft: "مسودة",
        sent: "مُرسل",
        accepted: "مقبول",
        declined: "مرفوض",
        expired: "منتهي",
        converted: "محوَّل",
      },
      kindLabels: { monthly: "شهري", setup: "رسوم تأسيس", one_off: "مرة واحدة" },
    },
    documents: {
      invoice: "فاتورة",
      receipt: "سند قبض",
      statement: "كشف حساب",
      statementHint: "ملف PDF بكل المبالغ المستحقة على هذا العميل.",
      bulkInvoices: "كل الفواتير المستحقة (PDF)",
      bulkOverdue: "المتأخرة فقط (PDF)",
      noneDue: "لا توجد مبالغ مستحقة حالياً.",
    },
    settings: {
      title: "إعدادات الشركة والفواتير",
      intro: "تظهر هذه البيانات في كل فاتورة وسند قبض وكشف حساب.",
      nameEn: "اسم الشركة (إنجليزي)",
      nameAr: "اسم الشركة (عربي)",
      vatNumber: "الرقم الضريبي",
      vatHint: "مطلوب للفواتير الضريبية ورمز QR الخاص بهيئة الزكاة والضريبة.",
      crNumber: "رقم السجل التجاري",
      addressEn: "العنوان (إنجليزي)",
      addressAr: "العنوان (عربي)",
      phone: "الهاتف",
      email: "البريد الإلكتروني",
      website: "الموقع الإلكتروني",
      bankName: "اسم البنك",
      iban: "رقم الآيبان",
      invoicePrefix: "بادئة رقم الفاتورة",
      receiptPrefix: "بادئة رقم السند",
      quotePrefix: "بادئة رقم عرض السعر",
      quoteValidity: "مدة صلاحية عرض السعر (أيام)",
      prefixHint: "تُستخدم بصيغة PREFIX-YEAR-00001. التغيير يؤثر على المستندات الجديدة فقط.",
      paymentTermsEn: "شروط السداد / ملاحظة (إنجليزي)",
      paymentTermsAr: "شروط السداد / ملاحظة (عربي)",
      save: "حفظ الإعدادات",
      saved: "تم حفظ الإعدادات.",
      adminOnly: "التعديل متاح للمشرفين فقط.",
    },
    login: {
      title: "تسجيل الدخول",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      submit: "دخول",
      error: "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
    },
    dashboard: {
      title: "لوحة التحكم",
      upcomingReminders: "التذكيرات القادمة",
      overduePayments: "المدفوعات المتأخرة",
      totalClients: "إجمالي العملاء",
      outstanding: "المستحق",
      advanceHeld: "رصيد مقدم",
      noReminders: "لا توجد تذكيرات قريبة.",
      noOverdue: "لا توجد مدفوعات متأخرة.",
      viewAll: "عرض الكل",
    },
    clients: {
      title: "العملاء",
      new: "عميل جديد",
      name: "الاسم",
      company: "اسم النشاط التجاري",
      email: "البريد الإلكتروني",
      phone: "الهاتف",
      whatsapp: "واتساب",
      industry: "المجال",
      status: "الحالة",
      website: "الموقع الإلكتروني",
      startDate: "تاريخ البدء",
      primaryService: "الخدمة الأساسية",
      gmbName: "اسم النشاط على Google",
      gmbLocation: "موقع النشاط على Google",
      gmbLink: "رابط النشاط على Google",
      vatNumber: "الرقم الضريبي",
      notes: "ملاحظات",
      assignedTo: "المسؤول",
      unassigned: "غير مُسند",
      selectService: "اختر خدمة",
      save: "حفظ",
      delete: "حذف",
      confirmDelete:
        "هل تريد حذف هذا العميل وكل خدماته ورسومه ودفعاته وعروض أسعاره؟ لا يمكن التراجع عن هذا الإجراء.",
      search: "بحث بالاسم أو النشاط أو البريد أو الهاتف...",
      searchButton: "بحث",
      empty: "لا يوجد عملاء بعد.",
      emptyFiltered: "لا يوجد عملاء مطابقون لهذه الفلاتر.",
      tags: "الوسوم",
      tagsHint: "مفصولة بفواصل — مثال: VIP، الرياض، إحالة",
      allStatuses: "كل الحالات",
      allServices: "كل الخدمات",
      anyStaff: "أي موظف",
      noStaff: "غير المُسند فقط",
      allTags: "كل الوسوم",
      sortNewest: "الأحدث أولاً",
      sortOldest: "الأقدم أولاً",
      sortName: "الاسم أبجدياً",
      reset: "إعادة تعيين",
      exportCsv: "تصدير CSV",
      contact: "التواصل",
      outstanding: "المستحق",
      added: "تاريخ الإضافة",
      pageLabel: "صفحة",
      of: "من",
      prev: "السابق",
      next: "التالي",
      statsTotal: "إجمالي العملاء",
      statsOutstanding: "إجمالي المستحق",
      statsOverdue: "لديهم متأخرات",
      statusLabels: { lead: "عميل محتمل", active: "نشط", paused: "متوقف", churned: "منسحب" },
      serviceLabels: {
        seo: "تحسين محركات البحث",
        local_seo_gmb: "SEO محلي / نشاط Google",
        web_design: "تصميم المواقع",
        web_development: "تطوير المواقع",
        google_ads_ppc: "إعلانات Google / الدفع بالنقرة",
        social_media: "وسائل التواصل الاجتماعي",
        content_blogs: "المحتوى / المدونات",
        google_ads_fee: "رسوم إعلانات Google",
        gmb_creation_fee: "رسوم إنشاء نشاط Google",
      },
    },
    services: {
      title: "الخدمات",
      add: "إضافة خدمة",
      service: "الخدمة",
      status: "الحالة",
      startedAt: "تاريخ البدء",
      endedAt: "تاريخ الانتهاء",
      notes: "ملاحظات",
      empty: "لا توجد خدمات مسجلة بعد.",
      current: "الحالية",
      past: "السابقة",
      statusLabels: { active: "نشطة", completed: "مكتملة", paused: "متوقفة" },
      markActive: "تفعيل",
      markPaused: "إيقاف",
      markCompleted: "إكمال",
      delete: "إزالة",
      confirmDelete: "هل تريد إزالة هذه الخدمة من السجل؟",
    },
    clientNotes: {
      title: "سجل الملاحظات",
      placeholder: "اكتب ملاحظة — ملخص مكالمة، قرار، خطوة قادمة...",
      save: "إضافة ملاحظة",
      pin: "تثبيت",
      unpin: "إلغاء التثبيت",
      delete: "حذف",
      empty: "لا توجد ملاحظات بعد.",
      confirmDelete: "هل تريد حذف هذه الملاحظة؟",
    },
    activity: {
      title: "النشاط",
      empty: "لا يوجد نشاط مسجل بعد.",
      kindLabels: {
        client_created: "تم إنشاء العميل",
        client_updated: "تم تحديث البيانات",
        status_changed: "تغيرت الحالة",
        service_added: "أُضيفت خدمة",
        service_status: "تغيرت حالة خدمة",
        service_removed: "أُزيلت خدمة",
        plan_created: "أُنشئت خطة فوترة",
        plan_updated: "عُدلت خطة الفوترة",
        charge_created: "أُنشئ رسم",
        charge_deleted: "حُذف رسم",
        payment_received: "استُلمت دفعة",
        receipt_deleted: "حُذف سند قبض",
        quotation_created: "أُنشئ عرض سعر",
        quotation_status: "تغيرت حالة عرض سعر",
        expense_added: "سُجل مصروف",
        expense_deleted: "حُذف مصروف",
      },
    },
    payments: {
      title: "الرسوم",
      new: "رسم جديد",
      client: "العميل",
      description: "الوصف",
      amount: "المبلغ",
      currency: "العملة",
      dueDate: "تاريخ الاستحقاق",
      status: "الحالة",
      kind: "النوع",
      period: "الشهر المُحاسب عليه",
      periodHint: "للرسوم الشهرية فقط. رسم واحد لكل عميل في الشهر.",
      invoiceNumber: "رقم الفاتورة",
      markPaid: "تحديد كمدفوع بالكامل",
      confirmDelete: "هل تريد حذف هذا الرسم؟",
      overdue: "متأخر",
      save: "حفظ",
      empty: "لا توجد رسوم بعد.",
      subtotal: "المجموع الفرعي",
      vat: "إضافة ضريبة 15%",
      vatAmount: "الضريبة (15%)",
      adBudget: "ميزانية إعلانات — مال العميل للإعلانات وليس إيرادنا",
      adBudgetShort: "ميزانية إعلانات",
      total: "الإجمالي",
      received: "المستلم",
      balance: "المتبقي",
      generate: "إنشاء الرسوم المستحقة",
      generateHint: "ينشئ الرسوم الشهرية ورسوم التأسيس المستحقة. يمكن تشغيله أكثر من مرة بأمان.",
      generated: "رسم/رسوم تم إنشاؤها",
      upToDate: "كل الرسوم منشأة بالفعل.",
      statusLabels: { unpaid: "غير مدفوع", partial: "مدفوع جزئياً", paid: "مدفوع" },
      kindLabels: { monthly: "شهري", setup: "رسوم تأسيس", one_off: "مرة واحدة" },
    },
    billing: {
      title: "خطة الفوترة",
      none: "لا توجد خطة فوترة بعد — أضف واحدة لفوترة هذا العميل شهرياً بشكل تلقائي.",
      monthlyAmount: "المبلغ الشهري",
      adBudgetAmount: "ميزانية الإعلانات الشهرية",
      adBudgetHint: "تُفوتر كل شهر كرسم ميزانية إعلانات منفصل، بدون ضريبة.",
      setupFee: "رسوم التأسيس / أول مرة",
      setupFeeHint: "تُحتسب مرة واحدة عند بدء الخطة (مثل إنشاء نشاط Google).",
      setupFeeCharged: "تم احتساب رسوم التأسيس بالفعل.",
      billingDay: "يوم الفوترة من الشهر",
      billingDayHint: "من 1 إلى 28 حتى تعمل في كل الأشهر.",
      startDate: "بداية الخطة",
      endDate: "نهاية الخطة (اختياري)",
      vatEnabled: "إضافة ضريبة 15% على رسوم هذه الخطة",
      status: "حالة الخطة",
      statusLabels: { active: "نشطة", paused: "متوقفة", ended: "منتهية" },
      save: "حفظ الخطة",
      perMonth: "/شهرياً",
      outstanding: "المستحق",
      credit: "رصيد مقدم",
      totalCharged: "إجمالي الفوترة",
      totalReceived: "إجمالي المستلم",
      creditHint: "مدفوع مقدماً — يُطبَّق تلقائياً على الرسم التالي.",
    },
    receipts: {
      title: "الدفعات المستلمة",
      record: "تسجيل دفعة",
      amount: "المبلغ المستلم",
      receivedAt: "تاريخ الاستلام",
      method: "طريقة الدفع",
      reference: "المرجع / رقم العملية",
      notes: "ملاحظات",
      applyTo: "تطبيق على",
      applyAuto: "أقدم رسم غير مدفوع أولاً (موصى به)",
      applyCredit: "الاحتفاظ به كرصيد مقدم",
      unapplied: "غير مطبَّق",
      empty: "لا توجد دفعات مسجلة بعد.",
      delete: "حذف",
      confirmDelete: "هل تريد حذف هذه الدفعة؟ سيتم عكس تطبيقها على الرسوم.",
      save: "حفظ الدفعة",
      methodLabels: {
        bank: "تحويل بنكي",
        cash: "نقداً",
        stc_pay: "STC Pay",
        card: "بطاقة",
        cheque: "شيك",
        other: "أخرى",
      },
    },
    reminders: {
      title: "التذكيرات",
      new: "تذكير جديد",
      client: "العميل (اختياري)",
      reminderTitle: "العنوان",
      description: "الوصف",
      dueAt: "الموعد",
      channels: "القنوات",
      markDone: "تحديد كمنجز",
      dismiss: "تجاهل",
      save: "حفظ",
      empty: "لا توجد تذكيرات بعد.",
      channelLabels: { dashboard: "لوحة التحكم", email: "البريد الإلكتروني", whatsapp: "واتساب" },
      statusLabels: { pending: "قيد الانتظار", sent: "أُرسل", done: "منجز", dismissed: "متجاهل" },
    },
    team: {
      title: "الفريق",
      role: "الدور",
      active: "نشط",
      makeAdmin: "ترقية لمشرف",
      makeStaff: "تنزيل لموظف",
      deactivate: "تعطيل",
      activate: "تفعيل",
      adminOnly: "للمشرفين فقط.",
    },
    common: {
      cancel: "إلغاء",
      edit: "تعديل",
      back: "رجوع",
      loading: "جاري التحميل...",
      requiredField: "هذا الحقل مطلوب.",
      genericError: "حدث خطأ ما. حاول مرة أخرى.",
    },
  },
} as const;

export function getDict(lang: ManageLang) {
  return manageDict[lang];
}
